#pragma once

#define GERNETIX_USER_PWM_PIN 2
#define GERNETIX_USER_PWM_CHANNEL 0
#define GERNETIX_USER_PWM_FREQUENCY_HZ 1000
#define GERNETIX_USER_PWM_RESOLUTION_BITS 8
#define GERNETIX_USER_PWM_DUTY_MIN 0
#define GERNETIX_USER_PWM_DUTY_MAX 255
#define GERNETIX_USER_PWM_STEPS 10
#define GERNETIX_USER_PWM_STEP_INTERVAL_MS 250
