[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
upload_protocol = esptool
board_build.flash_size = 4MB
board_build.partitions = partitions_ota_4mb.csv
build_flags = -D GERNETIX_BASISSOFTWARE_PROFILE_FULL=1
board_upload.flash_size = 4MB

[env:esp32dev-medium]
extends = env:esp32dev
board_build.partitions = partitions_medium_4mb.csv
build_flags = -D GERNETIX_BASISSOFTWARE_PROFILE_MEDIUM=1

[env:esp32dev-low]
extends = env:esp32dev
board_build.partitions = partitions_low_4mb.csv
build_flags = -D GERNETIX_BASISSOFTWARE_PROFILE_LOW=1
