[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_protocol = esptool

build_flags =
  -I src
  -D GERNETIX_FIRMWARE_NAME=\"gernetix-esp32-basissoftware\"
  -D GERNETIX_FIRMWARE_VERSION=\"0.1.0\"
