const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const authRoot = path.join(__dirname, "..", "public", "app", "auth");
const publicRoot = path.join(__dirname, "..", "public");
const html = fs.readFileSync(path.join(authRoot, "index.html"), "utf8");
const css = fs.readFileSync(path.join(authRoot, "auth.css"), "utf8");
const script = fs.readFileSync(path.join(authRoot, "auth.js"), "utf8");
const publicHeaderCss = fs.readFileSync(path.join(publicRoot, "public-header.css"), "utf8");
const publicHeaderScript = fs.readFileSync(path.join(publicRoot, "landing.js"), "utf8");

test("uses the one public GerNetiX header and burger menu on the authentication page", () => {
  assert.match(html, /class="site-header"/);
  assert.match(html, /src="\/gernetix-wordmark\.png"[\s\S]*alt="GerNetiX"/);
  assert.match(html, /id="publicMenuButton"[\s\S]*aria-controls="publicMenu"/);
  assert.match(html, /id="publicMenu"[\s\S]*href="\/nachbauprojekte\/"[\s\S]*href="\/community\/"/);
  assert.match(html, /id="publicMenu"[\s\S]*href="\/tarife\/"[\s\S]*href="\/shop\/"/);
  assert.match(html, /href="\/public-header\.css/);
  assert.match(html, /src="\/landing\.js/);
  assert.match(publicHeaderCss, /\.site-header/);
  assert.match(publicHeaderCss, /\.menu-button/);
  assert.match(css, /\[hidden\]\s*\{\s*display:\s*none !important;/);
  assert.match(publicHeaderScript, /menuButton\?\.addEventListener/);
  assert.doesNotMatch(script, /authMenuButton|authMenu|closeAuthMenu/);
  assert.doesNotMatch(css, /auth-site-header|auth-menu-button|auth-site-menu/);
  assert.doesNotMatch(html, /class="brand-mark" aria-hidden="true">G/);
  assert.match(html, /class="guest-access"[\s\S]*Als Gast starten/);
  assert.match(html, /Passwort\/Passkey vergessen/);
  assert.match(html, /id="login-identifier-field"(?![^>]*hidden)/);
  assert.match(html, /id="login-identifier"[^>]*placeholder="z\. B\. sven02"/);
  assert.match(html, /Vorläufiges Support-Passwort verwenden/);
  assert.match(html, /id="support-recovery-form"/);
  assert.equal((html.match(/data-i18n="auth\.passkey\.qr_hint"/g) || []).length, 2);
  assert.match(html, /QR-Code[\s\S]*Smartphone oder Tablet/);
  assert.match(css, /\.passkey-qr-hint/);
  assert.match(script, /\/api\/recovery\/offline\/start/);
  assert.match(script, /\/api\/recovery\/offline\/passkey\/options/);
  assert.match(script, /\/api\/recovery\/offline\/passkey\/verify/);
  assert.match(script, /\/api\/recovery\/support\/login/);
  assert.match(script, /\/api\/recovery\/support\/passkey\/options/);
  assert.match(script, /\/api\/recovery\/support\/passkey\/verify/);
  assert.match(publicHeaderScript, /id="publicLanguage"[\s\S]*Deutsch[\s\S]*English[\s\S]*Nederlands/);
  assert.match(publicHeaderScript, /DE · EN · NL/);
  assert.match(html, /\/app\/i18n\/i18n\.js/);
  assert.match(publicHeaderScript, /window\.GerNetiXI18n\.create\(\)/);
  assert.match(script, /locale: currentLocale\(\)/);
  assert.doesNotMatch(script, /sessionStorage/);
  assert.doesNotMatch(script, /localStorage/);
  assert.match(html, /class="auth-site-footer"[\s\S]*Über uns[\s\S]*Wissensportal[\s\S]*Hilfe/);
  assert.doesNotMatch(html, /href="\/app\/vision\/"/);
  assert.match(css, /\.auth-site-footer/);
});
