const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const publicRoot = path.resolve(__dirname, "../public/app");
const html = fs.readFileSync(path.join(publicRoot, "index.html"), "utf8");
const app = fs.readFileSync(path.join(publicRoot, "app.js"), "utf8");
const server = fs.readFileSync(path.join(__dirname, "..", "src", "dev-server.js"), "utf8");

test("build and flash actions expose their concrete prerequisite without becoming inert", () => {
  assert.match(html, /id="ideActionReason"/);
  assert.equal((html.match(/aria-describedby="ideActionReason"/g) || []).length, 3);
  assert.match(html, /id="ideBuildConsole"/);
  assert.match(html, /id="ideTerminalOutput"/);
  assert.match(html, /id="clearIdeTerminalButton"/);
  assert.match(html, /id="usbFlashButton"[^>]*>USB</);
  assert.doesNotMatch(html, /id="usbFlashButton"[^>]*aria-describedby="ideActionReason"/);
  assert.match(html, /id="otaFlashButton"[^>]*>OTA</);
  assert.match(html, /id="flashBoxFlashButton"[^>]*>FlashBox</);
  assert.match(app, /function ideActionUnavailableReason/);
  assert.match(app, /Für OTA ist kein kompatibles Board im Inventar/);
  assert.match(app, /Build und direkter USB-Flash funktionieren auch ohne diese Zuordnung/);
  assert.match(app, /meldet den OTA-Status/);
  assert.match(app, /buildButton\.disabled = false/);
  assert.match(app, /usbButton\.disabled = !supportedFlashTarget/);
  assert.match(app, /otaButton\.disabled = !supportedFlashTarget \|\| !allocated/);
  assert.match(app, /flashBoxButton\.disabled = !supportedFlashTarget \|\| !flashboxes\.length/);
  assert.match(html, /id="checkOtaConnectivityButton"/);
  assert.match(app, /Direkter USB-Flash verwendet die Projekt-Boardkonfiguration/);
  assert.match(app, /navigator\.serial\.requestPort/);
  assert.match(app, /flashBuildViaSerialService/);
  assert.match(app, /state\.serialService\.flash/);
  assert.match(server, /function browserFlashManifest\(jobId, completedJob, buildConfig = \{\}\)/);
  assert.match(server, /function esp32BootloaderAddress\(buildConfig = \{\}\)[\s\S]*esp32\[-_\]\?s3\|es3c28p[\s\S]*\? 0x0000 : 0x1000/);
  assert.match(app, /loadIdeEsptoolModule/);
  assert.match(app, /browser-usb-flash-result/);
  assert.match(app, /Automatisch \(kein USB-Port erkannt\)/);
  assert.match(app, /if \(!resolvedPort && state\.usbPorts\.length > 1\)/);
  assert.doesNotMatch(html, /id="refreshUsbPortsButton"/);
  assert.doesNotMatch(html, /id="ideDeviceTools"[\s\S]*id="usbPortSelect"/);
  assert.match(html, /id="usbPortChoiceDialog"[\s\S]*id="usbPortSelect"/);
  assert.match(app, /if \(!resolvedPort && state\.usbPorts\.length > 1\) \{\s*showUsbPortChoiceDialog\(\)/);
  assert.match(app, /function showUsbPortMissingGuidance/);
  assert.match(html, /id="usbPortMissingDialog"/);
  assert.match(html, /id="retryUsbPortSearchButton"/);
  assert.match(html, /Das Board benötigt einen Reset/);
  assert.match(html, /Suchen und Flash fortsetzen/);
  assert.match(html, /Die Firmware startet USB\/Serial nicht oder hängt beim Neustart/);
  assert.match(html, /USB-Stecker und Stromversorgung angeschlossen lassen/);
  assert.match(html, /nur RESET startet normalerweise wieder dieselbe fehlerhafte Firmware/);
  assert.match(html, /BOOT gedrückt halten/);
  assert.match(html, /RESET zusätzlich drücken/);
  assert.match(html, /RESET zuerst loslassen/);
  assert.match(html, /BOOT danach loslassen/);
  assert.match(html, /ROM-Download-Modus und führt die Projektfirmware nicht aus/);
  assert.match(app, /async function startUsbFlash\(targetConfirmed = false\)[\s\S]*await refreshUsbPorts\(false\);[\s\S]*if \(!state\.usbPorts\.length\) \{[\s\S]*state\.pendingUsbFlash = \{ mode: "start", projectId: project\.id \};[\s\S]*showUsbPortMissingGuidance\(\)/);
  assert.doesNotMatch(app, /async function refreshUsbPorts\(showStatus = true\)[\s\S]*if \(showStatus && !state\.usbPorts\.length\) showUsbPortMissingGuidance\(\)/);
  assert.match(app, /state\.pendingUsbFlash = \{ mode: "start", projectId: project\.id \}/);
  assert.match(app, /async function retryUsbPortSearch\(\)[\s\S]*Flash-Vorgang wird fortgesetzt[\s\S]*await resumeUsbFlashWithCompletedBuild\(pending\)[\s\S]*await startUsbFlash\(true\)/);
  assert.match(app, /async function resumeUsbFlashWithCompletedBuild\(pending\)[\s\S]*flashBuildViaSerialService\(build, device\)/);
  assert.doesNotMatch(app, /<details class="ide-tree-folder"[^>]* open>/);
  assert.doesNotMatch(app, /function projectRealizationsTreeEntry/);
  assert.doesNotMatch(app, /Architektur\/Realisierungen/);
  assert.doesNotMatch(app, /data-project-realizations|<h3>Inventar-Device zuordnen<\/h3>/);
  assert.match(app, /function isArchitectureBaselinePath/);
  assert.match(app, /Freigegebene Architektur-Baseline/);
  assert.match(app, /!ideSourceIsEditable\(project, state\.sourcePath\)/);
  assert.match(app, /component_device_allocations/);
  assert.match(app, /function appendIdeTerminal/);
  assert.match(app, /setUsbFlashSuccess\(`USB-Flash erfolgreich: \$\{flashResult\.chipName\}`\)/);
  assert.match(app, /function setUsbFlashSuccess\(text\)[\s\S]*status\.className = "flash-status hidden";[\s\S]*appendIdeTerminal\("ok", text\)/);
  assert.match(html, /id="flashboxDeviceSelect"/);
  assert.match(app, /activeFlashboxDeviceId/);
  assert.match(app, /Waehle zuerst eine verfuegbare FlashBox/);
  assert.match(server, /flashbox_not_in_inventory/);
  assert.match(server, /flashbox_cannot_be_target/);
});

test("plain project build and direct USB flash do not require an inventory device", () => {
  const app = fs.readFileSync(path.join(__dirname, "..", "public", "app", "app.js"), "utf8");

  assert.match(app, /device_id: device\?\.device_id \|\| ""/);
  assert.match(server, /if \(!device && !\["build", "build_and_usb_flash"\]\.includes\(mode\)\)/);
  assert.match(server, /const resolvedBuildConfig = softwareUnit\?\.build_config \|\| resolveBuildConfig\(project, device \|\| \{\}\)/);
  assert.match(server, /build_config: resolvedBuildConfig/);
  assert.match(app, /async function startUsbFlash\(targetConfirmed = false\)[\s\S]*if \(!project\) return setFlashStatus\("error", "Bitte zuerst ein Projekt öffnen\."\)/);
  assert.match(server, /body\.upload_port \|\| device\?\.upload_port/);
  assert.doesNotMatch(server, /mode === "build_and_usb_flash" && !device\.usb_flash_supported/);
});
