const { readPlatformAppSource } = require("../test-support/platform-app-source");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const publicRoot = path.resolve(__dirname, "../public/app");
const html = fs.readFileSync(path.join(publicRoot, "index.html"), "utf8");
const css = fs.readFileSync(path.join(publicRoot, "app.css"), "utf8");
const app = readPlatformAppSource();
const flashProgress = fs.readFileSync(path.join(publicRoot, "flash-progress.js"), "utf8");
const server = fs.readFileSync(path.join(__dirname, "..", "src", "dev-server.js"), "utf8");

test("build and flash actions expose their concrete prerequisite without becoming inert", () => {
  assert.match(html, /id="ideActionReason"/);
  assert.equal((html.match(/aria-describedby="ideActionReason"/g) || []).length, 3);
  assert.match(html, /id="ideBuildConsole"/);
  assert.match(html, /flash-progress\.js\?v=20260802-flash-progress/);
  assert.match(html, /id="ideTerminalOutput"/);
  assert.match(html, /id="clearIdeTerminalButton"/);
  assert.match(html, /id="usbFlashButton"[^>]*>USB</);
  assert.doesNotMatch(html, /id="usbFlashButton"[^>]*aria-describedby="ideActionReason"/);
  assert.match(html, /id="otaFlashButton"[^>]*>OTA</);
  assert.match(html, /id="flashBoxFlashButton"[^>]*>FlashBox</);
  assert.match(app, /function ideActionUnavailableReason/);
  assert.match(app, /Für OTA ist kein kompatibles Board im Inventar/);
  assert.match(app, /Build und direkter USB-Flash funktionieren auch ohne diese Zuordnung/);
  assert.match(app, /meldet den OTA-Status/);
  assert.match(app, /function updateBuildActionButton[\s\S]*button\.disabled = false/);
  assert.match(app, /usbButton\.disabled = !supportedFlashTarget/);
  assert.match(app, /otaButton\.disabled = !supportedFlashTarget \|\| !allocated/);
  assert.match(app, /flashBoxButton\.disabled = !supportedFlashTarget \|\| !flashboxes\.length/);
  assert.match(html, /id="checkOtaConnectivityButton"/);
  assert.match(app, /Direkter USB-Flash verwendet die Projekt-Boardkonfiguration/);
  assert.match(app, /navigator\.serial\.requestPort/);
  assert.match(app, /flashBuildViaSerialService/);
  assert.match(app, /state\.serialService\.flash/);
  assert.match(app, /GerNetiXFlashProgress\.renderJob\("#flashStatus"/);
  assert.match(app, /precedingBytes\[index\]/);
  assert.match(flashProgress, /role", "progressbar"/);
  assert.match(css, /\.flash-progress-track\.indeterminate/);
  assert.match(server, /function browserFlashManifest\(jobId, completedJob, buildConfig = \{\}\)/);
  assert.match(server, /completeBrowserFlashDefinitions\(runnerManifest, fallbackDefinitions, \{/);
  assert.match(server, /authoritativeFallbackNames: usesGerNetixOtaAppLayout\(buildConfig\)/);
  assert.match(server, /function esp32BootloaderAddress\(buildConfig = \{\}\)[\s\S]*esp32\[-_\]\?s3\|es3c28p[\s\S]*\? 0x0000 : 0x1000/);
  assert.match(app, /loadIdeEsptoolModule/);
  assert.match(app, /browser-usb-flash-result/);
  assert.match(app, /Automatisch \(kein USB-Port erkannt\)/);
  assert.match(app, /UsbFlashTargetModel\.selectionMode\(firmwareUnits\.length, state\.usbPorts\.length\)/);
  assert.match(html, /usb-flash-target-model\.js\?v=20260801-partial-usb-flash/);
  assert.match(html, /app-device-build-controller\.js\?v=20260804-debug-session-1/);
  assert.doesNotMatch(html, /id="refreshUsbPortsButton"/);
  assert.doesNotMatch(html, /id="ideDeviceTools"[\s\S]*id="usbPortSelect"/);
  assert.match(html, /id="usbPortChoiceDialog"[\s\S]*id="usbPortSelect"/);
  assert.match(html, /id="usbFirmwareTargetSelect"/);
  assert.match(html, /id="usbAssignmentGrid"/);
  assert.match(html, /id="usbFirmwarePortRows"/);
  assert.match(html, /id="usbPortIdentificationDialog"/);
  assert.match(html, /id="usbPortIdentificationDialogTitle">Bitte jetzt das zugehörige Board abziehen/);
  assert.doesNotMatch(html, /id="usbFlashPortIdentification"/);
  assert.match(html, /Firmware aus dem Projekt/);
  assert.match(html, /COM-\/USB-Port für diese Firmware/);
  assert.match(css, /\.usb-port-choice-dialog \{[\s\S]*background: linear-gradient\(145deg, #102f4d, #0b2038\)/);
  assert.match(css, /\.usb-flash-assignment-table-head,[\s\S]*\.usb-flash-assignment-row \{[\s\S]*grid-template-columns:/);
  assert.match(css, /\.usb-flash-port-cell select/);
  assert.match(css, /\.usb-port-identification-dialog\s*\{[\s\S]*background: linear-gradient/);
  assert.match(html, /id="usbPortIdentityWarning"/);
  assert.match(html, /Firmware aus dem Projekt/);
  assert.match(html, /id="usbInventoryUnknownDialog"/);
  assert.match(html, /Board noch nicht im Inventar/);
  assert.match(html, /Arbeitsweisen wie <strong>OTA-Updates<\/strong>/);
  assert.match(html, /id="continueUnknownInventoryUsbFlashButton"[^>]*>Trotzdem per USB flashen</);
  assert.match(html, /id="addUnknownUsbDeviceToInventoryButton"[^>]*>Zum Inventar hinzufügen</);
  assert.match(html, /id="dismissUsbInventoryWarningCheckbox"[^>]*type="checkbox"/);
  assert.match(html, /Diesen Hinweis künftig nicht mehr anzeigen/);
  assert.match(app, /showUsbPortChoiceDialog\(project, "single-device-conflict"\)/);
  assert.match(app, /showUsbPortChoiceDialog\(project, "firmware-port-mapping"\)/);
  assert.match(app, /Nur ein USB-Gerät anschließen/);
  assert.match(app, /Firmware und USB-Ports zuordnen/);
  assert.match(app, /function renderUsbFlashAssignmentLists/);
  assert.match(app, /function latestBuildForUsbFirmware/);
  assert.match(app, /async function reusableBuildForUsbFlash/);
  assert.match(app, /reuse-usb-flash/);
  assert.match(app, /Vorhandener Build für/);
  assert.match(app, /Inkrementeller PlatformIO-Build wird gestartet/);
  assert.match(app, /<b>Letzter Build:<\/b>/);
  assert.doesNotMatch(app, /<span><b>Compiler:<\/b>/);
  assert.doesNotMatch(app, /<span><b>Einstieg:<\/b>/);
  assert.doesNotMatch(app, /<span><b>Quellen:<\/b>/);
  assert.match(app, /data-usb-firmware-port-select/);
  assert.match(app, /data-identify-usb-flash-port/);
  assert.match(app, /function identifyUsbFlashPortForFirmware/);
  assert.match(app, /function renderUsbPortIdentificationDialog/);
  assert.match(app, /function stopUsbFlashPortIdentification[\s\S]*renderUsbFlashAssignmentLists\(project\)[\s\S]*renderUsbPortMappingConfirmationState\(\)/);
  assert.match(app, /renderUsbPortIdentificationDialog\("detected"/);
  assert.match(app, /Bitte das Board für \$\{target\} wieder einstecken/);
  assert.match(app, /GerNetiXUsbPortDisconnectDetector\.create/);
  assert.match(app, /assignments\.set\(event\.context\.softwareUnitId, event\.path\)/);
  assert.match(app, /units\.length === 2 && state\.usbPorts\.length === 2/);
  assert.match(app, /assignments\.set\(remainingUnit\.software_unit_id, remainingPort\.port\)/);
  assert.match(app, /Das andere Board wird automatisch zugeordnet/);
  assert.match(app, /function selectedUsbFirmwarePortAssignments/);
  assert.match(app, /function startUsbFlashAssignmentBatch/);
  assert.match(app, /remaining: selectedAssignments/);
  assert.match(app, /Basissoftware/);
  assert.match(app, /1 Zuordnung flashen/);
  assert.match(app, /Nicht ausgewählt – diese Firmware wird nicht geflasht/);
  assert.match(app, /Ohne vorherige Provisionierung kann GerNetiX nicht eindeutig erkennen/);
  assert.match(app, /state\.activeSoftwareUnitIds\[project\.id\] = selectedUnitId/);
  assert.match(app, /if \(!inventoryCheckConfirmed && !usbInventoryWarningDismissed\(\) && !inventoryDeviceForUsbFlash\(device, resolvedPort\)\)/);
  assert.match(app, /function inventoryDeviceForUsbFlash\(allocatedDevice, port\)/);
  assert.match(app, /function usbInventoryWarningStorageKey\(\)[\s\S]*state\.account\?\.user_id \|\| state\.account\?\.username/);
  assert.match(app, /localStorage\.setItem\(usbInventoryWarningStorageKey\(\), "true"\)/);
  assert.match(app, /addEventListener\("close", persistUsbInventoryWarningPreference\)/);
  assert.match(app, /startUsbFlash\(true, true, true\)/);
  assert.match(app, /navigate\("\/app\/device-management\/provisioning\/"\)/);
  assert.match(app, /function showUsbPortMissingGuidance/);
  assert.match(html, /id="usbPortMissingDialog"/);
  assert.match(html, /id="retryUsbPortSearchButton"/);
  assert.match(html, /Das Board benötigt einen Reset/);
  assert.match(html, /Suchen und Flash fortsetzen/);
  assert.match(html, /Die Firmware startet USB\/Serial nicht oder hängt beim Neustart/);
  assert.match(html, /id="usbPortMacosSecurityHint" class="usb-port-macos-security-hint hidden"/);
  assert.match(html, /macOS: USB-Gerät sichtbar, aber kein Serial-Port/);
  assert.match(html, /Datenschutz &amp; Sicherheit → Verbinden von Zubehör erlauben/);
  assert.match(html, /„Automatisch, wenn entsperrt“/);
  assert.match(app, /macosSecurityHint\.classList\.toggle\("hidden", !\/mac\/i\.test\(clientPlatform\)\)/);
  assert.match(html, /USB-Stecker und Stromversorgung angeschlossen lassen/);
  assert.match(html, /nur RESET startet normalerweise wieder dieselbe fehlerhafte Firmware/);
  assert.match(html, /BOOT gedrückt halten/);
  assert.match(html, /RESET zusätzlich drücken/);
  assert.match(html, /RESET zuerst loslassen/);
  assert.match(html, /BOOT danach loslassen/);
  assert.match(html, /ROM-Download-Modus und führt die Projektfirmware nicht aus/);
  assert.match(app, /async function startUsbFlash\(targetConfirmed = false, inventoryCheckConfirmed = false, usbMappingConfirmed = false\)[\s\S]*await refreshUsbPorts\(false\);[\s\S]*if \(!state\.usbPorts\.length\) \{[\s\S]*state\.pendingUsbFlash = \{ mode: "start", projectId: project\.id \};[\s\S]*showUsbPortMissingGuidance\(\)/);
  assert.doesNotMatch(app, /async function refreshUsbPorts\(showStatus = true\)[\s\S]*if \(showStatus && !state\.usbPorts\.length\) showUsbPortMissingGuidance\(\)/);
  assert.match(app, /state\.pendingUsbFlash = \{ mode: "start", projectId: project\.id \}/);
  assert.match(app, /async function retryUsbPortSearch\(\)[\s\S]*Flash-Vorgang wird fortgesetzt[\s\S]*await resumeUsbFlashWithCompletedBuild\(pending\)[\s\S]*await startUsbFlash\(true\)/);
  assert.match(app, /async function resumeUsbFlashWithCompletedBuild\(pending\)[\s\S]*flashBuildViaSerialService\(build, device\)/);
  assert.doesNotMatch(app, /<details class="ide-tree-folder"[^>]* open>/);
  assert.doesNotMatch(app, /function projectRealizationsTreeEntry/);
  assert.doesNotMatch(app, /Architektur\/Realisierungen/);
  assert.doesNotMatch(app, /data-project-realizations|<h3>Inventar-Device zuordnen<\/h3>/);
  assert.match(app, /function isArchitectureBaselinePath/);
  assert.match(app, /Freigegebene Architektur-Baseline/);
  assert.match(app, /!ideSourceIsEditable\(project, state\.sourcePath\)/);
  assert.match(app, /component_device_allocations/);
  assert.match(app, /function appendIdeTerminal/);
  assert.match(app, /setUsbFlashSuccess\(`USB-Flash erfolgreich: \$\{flashResult\.chipName\}`\)/);
  assert.match(app, /function setUsbFlashSuccess\(text\)[\s\S]*status\.className = "flash-status hidden";[\s\S]*appendIdeTerminal\("ok", text\)/);
  assert.match(html, /id="flashboxDeviceSelect"/);
  assert.match(app, /activeFlashboxDeviceId/);
  assert.match(app, /Waehle zuerst eine verfuegbare FlashBox/);
  assert.match(server, /flashbox_not_in_inventory/);
  assert.match(server, /flashbox_cannot_be_target/);
});

test("plain project build and direct USB flash do not require an inventory device", () => {
  const app = readPlatformAppSource();

  assert.match(app, /device_id: device\?\.device_id \|\| ""/);
  assert.match(server, /if \(!device && !\["build", "build_and_usb_flash"\]\.includes\(mode\)\)/);
  assert.match(server, /const resolvedBuildConfig = softwareUnit\?\.build_config \|\| resolveBuildConfig\(project, device \|\| \{\}\)/);
  assert.match(server, /build_config: resolvedBuildConfig/);
  assert.match(app, /async function startUsbFlash\(targetConfirmed = false, inventoryCheckConfirmed = false, usbMappingConfirmed = false\)[\s\S]*if \(!project\) return setFlashStatus\("error", "Bitte zuerst ein Projekt öffnen\."\)/);
  assert.match(server, /body\.upload_port \|\| device\?\.upload_port/);
  assert.doesNotMatch(server, /mode === "build_and_usb_flash" && !device\.usb_flash_supported/);
});
