"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.join(__dirname, "..");
const read = (...segments) => fs.readFileSync(path.join(root, ...segments), "utf8");
const readLab = (...segments) => fs.readFileSync(path.join(root, "..", "..", "modules", "virtual-electronics-lab", ...segments), "utf8");
const readServerUtils = () => fs.readFileSync(path.join(root, "src", "dev", "http-utils.js"), "utf8");

test("publishes the modular virtual electronics labs", () => {
  const homepage = read("public", "index.html");
  const overview = readLab("index.html");
  const oscilloscope = readLab("labs", "oscilloscope.js");
  const multimeter = readLab("labs", "multimeter.js");
  const filters = readLab("labs", "filter-lab.js");
  const radio = readLab("labs", "radio-lab.js");
  const spectrum = readLab("labs", "spectrum-analyzer.js");
  const vna = readLab("labs", "network-analyzer.js");
  const logic = readLab("labs", "logic-analyzer.js");
  const pinMultiplexing = readLab("labs", "pin-multiplexing.js");
  const power = readLab("labs", "power-supply.js");
  const lcr = readLab("labs", "lcr-meter.js");
  const throughput = readLab("labs", "gpio-led-throughput.js");
  const pt1000Throughput = readLab("labs", "pt1000-adc-throughput.js");
  const buttonThroughput = readLab("labs", "button-digital-input-throughput.js");
  const pt1000ThroughputUiTest = readLab("test", "labs", "pt1000-adc-throughput-ui.test.mjs");
  const buttonThroughputUiTest = readLab("test", "labs", "button-digital-input-throughput-ui.test.mjs");
  const throughputRuntime = readLab("labs", "gpio-led-throughput-runtime.js");
  const httpUtils = readServerUtils();
  const dockerfile = fs.readFileSync(path.join(root, "..", "..", "docker", "identity-service.Dockerfile"), "utf8");
  const routes = read("src", "dev", "server", "web-routes.js");

  assert.match(homepage, /href="\/technik-labs\/">Virtuelles Elektroniklabor/);
  assert.match(oscilloscope, /Oszilloskop-Messübung/);
  assert.match(oscilloscope, /FFT \/ Frequenzansicht/);
  assert.match(oscilloscope, /Messübung · Signal unbekannt/);
  assert.match(oscilloscope, /Neues Signal/);
  assert.match(oscilloscope, /Messung auswerten/);
  assert.match(oscilloscope, /Tastkopf/);
  assert.match(oscilloscope, /Kopplung/);
  assert.match(oscilloscope, /Holdoff/);
  assert.match(oscilloscope, /Erfassung/);
  assert.doesNotMatch(oscilloscope, /Nachleuchten/);
  assert.match(oscilloscope, /requestAnimationFrame/);
  assert.match(oscilloscope, /Signal läuft frei über den Bildschirm/);
  assert.match(oscilloscope, /triggerLevel: 10/);
  assert.match(oscilloscope, /addKnob\(horizontal, "Zeit \/ DIV"/);
  assert.match(oscilloscope, /addKnob\(section, "V \/ DIV"/);
  assert.match(oscilloscope, /trigger-mode-indicators/);
  assert.match(oscilloscope, /GerNetiX DSO-2L/);
  assert.match(oscilloscope, /cursor-mode-indicators/);
  assert.match(oscilloscope, /Δt.*1\/Δt/);
  assert.match(oscilloscope, /ΔV/);
  assert.match(oscilloscope, /setPointerCapture/);
  assert.match(overview, /src="\.\/app\.js/);
  assert.match(overview, /styles\.css\?v=/);
  assert.match(overview, /id="labTemplateSelect"/);
  assert.match(readLab("app.js"), /listLabTemplates/);
  assert.match(readLab("app.js"), /loadSelectedTemplate/);
  assert.match(routes, /lab-template-\(\?:contract\|catalog\)\\\.mjs/);
  assert.match(overview, /id="labThemeToggle"/);
  assert.match(readLab("app.js"), /gernetix-public-theme/);
  assert.match(readLab("app.js"), /Helles Design einschalten/);
  assert.match(readLab("app.js"), /createGpioLedThroughputLab/);
  assert.match(readLab("app.js"), /createPt1000ThroughputLab/);
  assert.match(readLab("app.js"), /createButtonDigitalInputThroughputLab/);
  assert.match(readLab("app.js"), /createFreeCircuitSimulationLab/);
  assert.match(readLab("app.js"), /createGpioLedThroughputLab\(\),\n\s*createPt1000ThroughputLab\(\),/);
  assert.match(readLab("app.js"), /createPt1000ThroughputLab\(\),\n\s*createButtonDigitalInputThroughputLab\(\{ assistantClient: troubleshootingAssistantClient \}\),/);
  assert.match(routes, /free-simulation\\\/\[\^\/\]\+\\\.mjs/);
  assert.match(routes, /domain\\\/\[\^\/\]\+\\\.mjs/);
  assert.match(routes, /instruments\\\/\[\^\/\]\+\\\.mjs/);
  assert.match(readLab("app.js"), /createFilterLab/);
  assert.match(readLab("app.js"), /createRadioLab/);
  const labStyles = readLab("styles.css");
  assert.match(labStyles, /html\[data-public-theme=light\]/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.rotary-knob/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.instrument-button/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.oscilloscope-front-panel \.control-group/);
  assert.match(multimeter, /circuit-schematic/);
  assert.match(multimeter, /resistorH\(210, 320, 70, "R1", state\.resistance\)/);
  assert.match(multimeter, /schematic-led/);
  assert.match(multimeter, /probe-lead probe-red/);
  assert.match(multimeter, /probe-lead probe-black/);
  assert.match(multimeter, /Stromrückleitung/);
  assert.match(multimeter, /NPN-Transistorschalter/);
  assert.match(multimeter, /Emitterschaltung/);
  assert.match(multimeter, /Wheatstone-Messbrücke/);
  assert.doesNotMatch(multimeter, /RC-Tiefpass/);
  assert.match(multimeter, /Brücke links.*Brücke rechts/);
  assert.match(multimeter, /npnSymbol/);
  assert.match(filters, /Filter auslegen und vermessen/);
  assert.match(filters, /Sinusquelle Ueff/);
  assert.match(filters, /RC-Tiefpass/);
  assert.match(filters, /RC-Hochpass/);
  assert.match(filters, /RLC-Bandpass/);
  assert.match(filters, /Zweikanal-Messung/);
  assert.match(filters, /Frequenzgang/);
  assert.match(filters, /Bauteile auslegen/);
  assert.match(radio, /Radiolabor · AM und FM empfangen/);
  assert.match(radio, /Hallo GerNetiX/);
  assert.match(radio, /Guten Tag GerNetiX/);
  assert.match(radio, /AM · Hüllkurvendemodulator/);
  assert.match(radio, /FM · Superhet-Empfänger/);
  assert.match(radio, /carrier: 1000/);
  assert.match(radio, /10,7 MHz/);
  assert.match(radio, /Frequenzdiskriminator/);
  assert.match(radio, /SpeechSynthesisUtterance/);
  assert.match(radio, /createBufferSource/);
  assert.match(radio, /Math\.random\(\) \* 2 - 1/);
  assert.match(radio, /fmQuieting/);
  assert.match(radio, /whistle\.frequency/);
  assert.match(radio, /EMPFANG ANHÖREN/);
  assert.match(radio, /HF-Spektrum mit zwei unbekannten Sendern/);
  assert.match(radio, /AM_STATIONS/);
  assert.match(radio, /FM_STATIONS/);
  assert.match(radio, /drawRadioSpectrum/);
  assert.match(radio, /drawAmSpectrum/);
  assert.match(radio, /drawFmSpectrum/);
  assert.match(radio, /Carson: B ≈ 2/);
  assert.match(radio, /RC-Regel: Trägerperiode ≪ τ ≪ kürzeste Audioperiode/);
  assert.match(radio, /10 kΩ · 4,7 nF = 47 µs/);
  assert.match(radio, /Praxisbereich:/);
  assert.match(radio, /zu klein – Trägerwelligkeit/);
  assert.match(radio, /zu groß – Hüllkurve wird verschliffen/);
  assert.match(radio, /belegte Bandbreite/);
  assert.doesNotMatch(radio, /<h3>Moduliertes Signal<\/h3>/);
  assert.match(spectrum, /Nutzbar · Lernmodell/);
  assert.match(vna, /Smith-Diagramm/);
  assert.match(logic, /UART, I²C und SPI/);
  assert.match(power, /Konstantspannung \(CV\).*Konstantstrom \(CC\)/s);
  assert.match(lcr, /Impedanz und Phasenlage/);
  assert.match(throughput, /Durchstich · GPIO 5 → LED/);
  assert.match(throughput, /id="elab-throughput-source"/);
  assert.match(throughput, /data-action="start"/);
  assert.match(throughput, /data-action="reset"/);
  assert.match(throughput, /data-action="load-example"/);
  assert.match(throughput, /Generisches Lernmodell – keine ESP32-Emulation/);
  assert.match(throughput, /Formel: I_LED = max\(0, \(U_GPIO - U_F_LED\) \/ R\)/);
  assert.match(throughput, /data-output="gpio-level"/);
  assert.match(throughput, /data-output="gpio-voltage"/);
  assert.match(throughput, /data-output="led-current"/);
  assert.match(throughput, /data-output="led-mean-current"/);
  assert.match(throughput, /data-output="led-state"/);
  assert.match(throughput, /data-output="pwm-frequency"/);
  assert.match(throughput, /data-output="pwm-period"/);
  assert.match(throughput, /data-output="pwm-duty"/);
  assert.match(throughput, /data-output="pwm-high"/);
  assert.match(throughput, /data-output="pwm-low"/);
  assert.match(throughput, /elab-throughput-warnings/);
  assert.match(throughput, /Vom virtuellen zum echten Labor/);
  assert.match(throughput, /window\.confirm/);
  assert.match(throughput, /leadLines\.tip/);
  assert.doesNotMatch(throughput, /tipLines\./);
  assert.match(throughput, /loadFromRoute/);
  assert.match(pt1000Throughput, /Durchstich · PT1000 → ADC/);
  assert.match(pt1000Throughput, /id="pt1000-temperature-range"/);
  assert.match(pt1000Throughput, /id="pt1000-throughput-source"/);
  assert.match(pt1000Throughput, /data-action="start"/);
  assert.match(pt1000Throughput, /data-action="reset"/);
  assert.match(pt1000Throughput, /data-output="ambient-temperature"/);
  assert.match(pt1000Throughput, /data-output="sensor-resistance"/);
  assert.match(pt1000Throughput, /data-output="sense-voltage"/);
  assert.match(pt1000Throughput, /data-output="divider-current"/);
  assert.match(pt1000Throughput, /data-output="adc-code"/);
  assert.match(pt1000Throughput, /data-output="adc-quantized-voltage"/);
  assert.match(pt1000Throughput, /data-output="adc-variable"/);
  assert.match(pt1000Throughput, /Generisches Lernmodell – keine ESP32-Emulation/);
  assert.match(pt1000Throughput, /Vom virtuellen zum echten Labor/);
  assert.match(pt1000Throughput, /pt1000-throughput/);
  assert.match(pt1000Throughput, /textContent/);
  assert.match(pt1000Throughput, /COMMAND_TYPES/);
  assert.match(pt1000Throughput, /SetTemperature/);
  assert.match(pt1000Throughput, /UpdateSourceFile/);
  assert.match(pt1000Throughput, /StartSimulation/);
  assert.match(pt1000Throughput, /ResetSimulation/);
  assert.match(buttonThroughput, /Durchstich · Taster → digitalRead/);
  assert.match(buttonThroughput, /id="button-digital-input-throughput"/);
  assert.match(buttonThroughput, /id="button-throughput-source"/);
  assert.match(buttonThroughput, /data-action="toggle"/);
  assert.match(buttonThroughput, /data-action="start"/);
  assert.match(buttonThroughput, /data-action="reset"/);
  assert.match(buttonThroughput, /data-output="button-state"/);
  assert.match(buttonThroughput, /data-output="pull-mode"/);
  assert.match(buttonThroughput, /data-output="gpio-level"/);
  assert.match(buttonThroughput, /data-output="normalized-value"/);
  assert.match(buttonThroughput, /data-output="button-variable"/);
  assert.match(buttonThroughput, /data-output="pin"/);
  assert.match(buttonThroughput, /data-button-status/);
  assert.match(buttonThroughput, /data-button-warnings/);
  assert.match(buttonThroughput, /data-button-reality/);
  assert.match(buttonThroughput, /SetButtonPressed/);
  assert.match(buttonThroughput, /COMMAND_TYPES/);
  assert.match(buttonThroughput, /UpdateSourceFile/);
  assert.match(buttonThroughput, /StartSimulation/);
  assert.match(buttonThroughput, /ResetSimulation/);
  assert.match(buttonThroughput, /textContent/);
  assert.doesNotMatch(buttonThroughput, /pinMode/);
  assert.doesNotMatch(buttonThroughput, /digitalRead\s*\(/);
  assert.match(buttonThroughput, /Zeile \${entry\.line}, Spalte \${entry\.column}/);
  assert.match(buttonThroughput, /aria-pressed/);
  assert.match(buttonThroughput, /elab-button-throughput-layout/);
  assert.match(buttonThroughput, /elab-button-throughput-schematic/);
  assert.match(buttonThroughput, /elab-button-throughput-kpi/);
  assert.match(buttonThroughput, /elab-button-throughput-actions/);
  assert.match(buttonThroughput, /3,3 V/);
  assert.match(buttonThroughput, /GND/);
  assert.match(buttonThroughput, /Idealisiertes Lernmodell – keine ESP32-Emulation; Tasterprellen folgt einem festen Lehrprofil\./);
  assert.match(buttonThroughput, /createButtonBounceTrace/);
  assert.match(buttonThroughput, /data-bounce-cursor/);
  assert.match(buttonThroughput, /Idealisiert/);
  assert.match(buttonThroughputUiTest, /Runtime-Import statt Parser-/);
  assert.match(buttonThroughputUiTest, /Neuberechnung nach Tasterwechsel/);
  assert.match(buttonThroughputUiTest, /Eng begrenzte öffentliche Modulroute/);
  assert.match(buttonThroughputUiTest, /Kein Netzwerk, keine Persistenz, keine Clock, kein Zufall/);
  assert.match(pt1000ThroughputUiTest, /Runtime-Import statt doppelter Formel-Wahrheit/);
  assert.match(pt1000ThroughputUiTest, /Lab-Metadaten und Registrierung nach GPIO-LED-Durchstich/);
  assert.match(pt1000ThroughputUiTest, /Kein Netzwerk, keine Persistenz, keine Clock, kein Zufall/);
  assert.match(pt1000ThroughputUiTest, /Eng begrenzte öffentliche \.mjs-Module-Routen/);
  assert.equal(httpUtils.includes("\".mjs\": \"text/javascript; charset=utf-8\""), true);
  assert.match(throughputRuntime, /COMMAND_TYPES\s*=\s*\{/);
  assert.match(throughputRuntime, /pinMode\(5, OUTPUT\);/);
  assert.match(throughputRuntime, /digitalWrite\(5, HIGH\);/);
  assert.match(throughputRuntime, /HIGH\|LOW/);
  assert.match(throughputRuntime, /LoadLabExample/);
  assert.match(throughputRuntime, /pwmConfigure\(5, 1000, 25\);/);
  assert.match(throughputRuntime, /pwmStart\(5\);/);
  assert.match(throughputRuntime, /pwmStop\(5\);/);
  assert.match(throughputRuntime, /GPIO_SOURCE_CURRENT_EXCEEDED/);
  assert.match(throughputRuntime, /LED_CURRENT_EXCEEDED/);
  assert.doesNotMatch(throughputRuntime, /eval\(/);
  assert.doesNotMatch(throughputRuntime, /new\s+Function\(/);
  assert.doesNotMatch(throughputRuntime, /fetch\(/);
  assert.doesNotMatch(throughputRuntime, /XMLHttpRequest/);
  assert.doesNotMatch(throughputRuntime, /localStorage|sessionStorage/);
  assert.doesNotMatch(throughputRuntime, /requestAnimationFrame|setTimeout|Date\.now/);
  assert.doesNotMatch(throughput, /requestAnimationFrame|setTimeout|Date\.now/);
  assert.doesNotMatch(throughput, /type="range"/);
  assert.match(labStyles, /\.elab-throughput-layout/);
  assert.match(labStyles, /\.elab-throughput-kpi/);
  assert.match(labStyles, /\.elab-throughput-lead-lines/);
  assert.match(labStyles, /@media \(max-width: 580px\)[\s\S]*\.elab-throughput-kpi/);
  assert.match(labStyles, /@media \(max-width: 1100px\)[\s\S]*\.elab-throughput-layout/);
  assert.match(labStyles, /elab-pt1000-throughput-layout/);
  assert.match(labStyles, /@media \(max-width: 1280px\)[\s\S]*elab-pt1000-throughput-layout/);
  assert.match(labStyles, /@media \(max-width: 720px\)[\s\S]*elab-pt1000-throughput-layout/);
  assert.match(labStyles, /elab-button-throughput-layout/);
  assert.match(labStyles, /elab-button-throughput-kpi/);
  assert.match(labStyles, /\.elab-button-throughput-schematic/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.elab-button-throughput-schematic/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.elab-button-throughput-kpi/);
  assert.match(labStyles, /@media \(max-width: 1100px\)[\s\S]*elab-button-throughput-layout/);
  assert.match(labStyles, /@media \(max-width: 900px\)[\s\S]*elab-button-throughput-layout/);
  assert.match(labStyles, /@media \(max-width: 580px\)[\s\S]*elab-button-throughput-layout/);
  assert.match(spectrum, /Nutzbar · Lernmodell/);
  assert.match(vna, /Smith-Diagramm/);
  assert.match(logic, /UART, I²C und SPI/);
  assert.match(pinMultiplexing, /Projekt Arduino Nano/);
  assert.match(pinMultiplexing, /Projekt ESP32 Dev Board/);
  assert.match(pinMultiplexing, /ATmega328P/);
  assert.match(pinMultiplexing, /SPI SCLK · Board-LED/);
  assert.match(pinMultiplexing, /GPIO-Matrix[\s\S]*Strapping-Pin/);
  assert.match(pinMultiplexing, /Oszilloskop[\s\S]*Logikanalysator/);
  assert.match(pinMultiplexing, /Flashen deaktiviert/);
  assert.match(pinMultiplexing, /data-pinmux-action="conflict"/);
  assert.match(pinMultiplexing, /ADC2 und kollidiert im Lernmodell mit aktivem WLAN/);
  assert.match(readLab("app.js"), /createPinMultiplexingLab/);
  assert.match(readLab("app.js"), /lab-embedded/);
  assert.match(labStyles, /\.pinmux-instruments/);
  assert.match(power, /Konstantspannung \(CV\).*Konstantstrom \(CC\)/s);
  assert.match(lcr, /Impedanz und Phasenlage/);
  assert.match(dockerfile, /COPY --chown=node:node modules\/virtual-electronics-lab \.\/modules\/virtual-electronics-lab/);
  assert.match(routes, /\["\/technik-labs", "\/technik-labs\/"\][\s\S]*serveStatic\(res, virtualElectronicsLabDir, "\/index\.html"\)/);
  assert.ok(routes.includes("lab-template-(?:contract|catalog)\\.mjs"));
  assert.ok(routes.includes("ai\\/[^/]+\\.mjs"));
  assert.ok(routes.includes("labs\\/[^/]+\\.js"));
  assert.ok(routes.includes("serveStatic(res, virtualElectronicsLabDir, url.pathname.slice(\"/technik-labs\".length)"));
  assert.match(routes, /"\/technik-labs\/spektrumanalysator\/"[\s\S]*redirect\(res, "\/technik-labs\/\?lab=spectrum"\)/);
  assert.match(routes, /"\/technik-labs\/netzwerkanalysator\/"[\s\S]*redirect\(res, "\/technik-labs\/\?lab=vna"\)/);
  assert.doesNotMatch(routes, /path:\s*"\/technik-labs\/[^"]*\.html/);
  assert.doesNotMatch(routes, /fetch\('/);
});
