"use strict";

const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const test = require("node:test");

const root = path.join(__dirname, "..");
const read = (...segments) => fs.readFileSync(path.join(root, ...segments), "utf8");
const readLab = (...segments) => fs.readFileSync(path.join(root, "..", "..", "modules", "virtual-electronics-lab", ...segments), "utf8");

test("publishes the modular virtual electronics labs", () => {
  const homepage = read("public", "index.html");
  const overview = readLab("index.html");
  const oscilloscope = readLab("labs", "oscilloscope.js");
  const multimeter = readLab("labs", "multimeter.js");
  const filters = readLab("labs", "filter-lab.js");
  const radio = readLab("labs", "radio-lab.js");
  const spectrum = readLab("labs", "spectrum-analyzer.js");
  const vna = readLab("labs", "network-analyzer.js");
  const logic = readLab("labs", "logic-analyzer.js");
  const pinMultiplexing = readLab("labs", "pin-multiplexing.js");
  const power = readLab("labs", "power-supply.js");
  const lcr = readLab("labs", "lcr-meter.js");
  const dockerfile = fs.readFileSync(path.join(root, "..", "..", "docker", "identity-service.Dockerfile"), "utf8");
  const routes = read("src", "dev", "server", "web-routes.js");

  assert.match(homepage, /href="\/technik-labs\/">Virtuelles Elektroniklabor/);
  assert.match(oscilloscope, /Oszilloskop-Messübung/);
  assert.match(oscilloscope, /FFT \/ Frequenzansicht/);
  assert.match(oscilloscope, /Messübung · Signal unbekannt/);
  assert.match(oscilloscope, /Neues Signal/);
  assert.match(oscilloscope, /Messung auswerten/);
  assert.match(oscilloscope, /Tastkopf/);
  assert.match(oscilloscope, /Kopplung/);
  assert.match(oscilloscope, /Holdoff/);
  assert.match(oscilloscope, /Erfassung/);
  assert.doesNotMatch(oscilloscope, /Nachleuchten/);
  assert.match(oscilloscope, /requestAnimationFrame/);
  assert.match(oscilloscope, /Signal läuft frei über den Bildschirm/);
  assert.match(oscilloscope, /triggerLevel: 10/);
  assert.match(oscilloscope, /addKnob\(horizontal, "Zeit \/ DIV"/);
  assert.match(oscilloscope, /addKnob\(section, "V \/ DIV"/);
  assert.match(oscilloscope, /trigger-mode-indicators/);
  assert.match(oscilloscope, /GerNetiX DSO-2L/);
  assert.match(oscilloscope, /cursor-mode-indicators/);
  assert.match(oscilloscope, /Δt.*1\/Δt/);
  assert.match(oscilloscope, /ΔV/);
  assert.match(oscilloscope, /setPointerCapture/);
  assert.match(overview, /src="\.\/app\.js/);
  assert.match(overview, /id="labThemeToggle"/);
  assert.match(readLab("app.js"), /gernetix-public-theme/);
  assert.match(readLab("app.js"), /Helles Design einschalten/);
  const labStyles = readLab("styles.css");
  assert.match(labStyles, /html\[data-public-theme=light\]/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.rotary-knob/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.instrument-button/);
  assert.match(labStyles, /html\[data-public-theme=light\] \.oscilloscope-front-panel \.control-group/);
  assert.match(multimeter, /circuit-schematic/);
  assert.match(multimeter, /resistorH\(210, 320, 70, "R1", state\.resistance\)/);
  assert.match(multimeter, /schematic-led/);
  assert.match(multimeter, /probe-lead probe-red/);
  assert.match(multimeter, /probe-lead probe-black/);
  assert.match(multimeter, /Stromrückleitung/);
  assert.match(multimeter, /NPN-Transistorschalter/);
  assert.match(multimeter, /Emitterschaltung/);
  assert.match(multimeter, /Wheatstone-Messbrücke/);
  assert.doesNotMatch(multimeter, /RC-Tiefpass/);
  assert.match(multimeter, /Brücke links.*Brücke rechts/);
  assert.match(multimeter, /npnSymbol/);
  assert.match(filters, /Filter auslegen und vermessen/);
  assert.match(filters, /Sinusquelle Ueff/);
  assert.match(filters, /RC-Tiefpass/);
  assert.match(filters, /RC-Hochpass/);
  assert.match(filters, /RLC-Bandpass/);
  assert.match(filters, /Zweikanal-Messung/);
  assert.match(filters, /Frequenzgang/);
  assert.match(filters, /Bauteile auslegen/);
  assert.match(readLab("app.js"), /createFilterLab/);
  assert.match(radio, /Radiolabor · AM und FM empfangen/);
  assert.match(radio, /Hallo GerNetiX/);
  assert.match(radio, /Guten Tag GerNetiX/);
  assert.match(radio, /AM · Hüllkurvendemodulator/);
  assert.match(radio, /FM · Superhet-Empfänger/);
  assert.match(radio, /carrier: 1000/);
  assert.match(radio, /10,7 MHz/);
  assert.match(radio, /Frequenzdiskriminator/);
  assert.match(radio, /SpeechSynthesisUtterance/);
  assert.match(radio, /createBufferSource/);
  assert.match(radio, /Math\.random\(\) \* 2 - 1/);
  assert.match(radio, /fmQuieting/);
  assert.match(radio, /whistle\.frequency/);
  assert.match(radio, /EMPFANG ANHÖREN/);
  assert.match(radio, /HF-Spektrum mit zwei unbekannten Sendern/);
  assert.match(radio, /AM_STATIONS/);
  assert.match(radio, /FM_STATIONS/);
  assert.match(radio, /drawRadioSpectrum/);
  assert.match(radio, /drawAmSpectrum/);
  assert.match(radio, /drawFmSpectrum/);
  assert.match(radio, /Carson: B ≈ 2/);
  assert.match(radio, /RC-Regel: Trägerperiode ≪ τ ≪ kürzeste Audioperiode/);
  assert.match(radio, /10 kΩ · 4,7 nF = 47 µs/);
  assert.match(radio, /Praxisbereich:/);
  assert.match(radio, /zu klein – Trägerwelligkeit/);
  assert.match(radio, /zu groß – Hüllkurve wird verschliffen/);
  assert.match(radio, /belegte Bandbreite/);
  assert.doesNotMatch(radio, /<h3>Moduliertes Signal<\/h3>/);
  assert.match(readLab("app.js"), /createRadioLab/);
  assert.match(labStyles, /\.schematic-meter/);
  assert.match(spectrum, /Nutzbar · Lernmodell/);
  assert.match(vna, /Smith-Diagramm/);
  assert.match(logic, /UART, I²C und SPI/);
  assert.match(pinMultiplexing, /Projekt Arduino Nano/);
  assert.match(pinMultiplexing, /Projekt ESP32 Dev Board/);
  assert.match(pinMultiplexing, /ATmega328P/);
  assert.match(pinMultiplexing, /SPI SCLK · Board-LED/);
  assert.match(pinMultiplexing, /GPIO-Matrix[\s\S]*Strapping-Pin/);
  assert.match(pinMultiplexing, /Oszilloskop[\s\S]*Logikanalysator/);
  assert.match(pinMultiplexing, /Flashen deaktiviert/);
  assert.match(pinMultiplexing, /data-pinmux-action="conflict"/);
  assert.match(pinMultiplexing, /ADC2 und kollidiert im Lernmodell mit aktivem WLAN/);
  assert.match(readLab("app.js"), /createPinMultiplexingLab/);
  assert.match(readLab("app.js"), /lab-embedded/);
  assert.match(labStyles, /\.pinmux-instruments/);
  assert.match(power, /Konstantspannung \(CV\).*Konstantstrom \(CC\)/s);
  assert.match(lcr, /Impedanz und Phasenlage/);
  assert.match(dockerfile, /COPY --chown=node:node modules\/virtual-electronics-lab \.\/modules\/virtual-electronics-lab/);
  assert.match(routes, /\["\/technik-labs", "\/technik-labs\/"\][\s\S]*serveStatic\(res, virtualElectronicsLabDir, "\/index\.html"\)/);
  assert.match(routes, /"\/technik-labs\/spektrumanalysator\/"[\s\S]*redirect\(res, "\/technik-labs\/\?lab=spectrum"\)/);
  assert.match(routes, /"\/technik-labs\/netzwerkanalysator\/"[\s\S]*redirect\(res, "\/technik-labs\/\?lab=vna"\)/);
});
