#!/bin/sh
set -eu

psql --set=ON_ERROR_STOP=1 \
  --set=forgejo_password="$FORGEJO_POSTGRES_PASSWORD" \
  --username "$POSTGRES_USER" \
  --dbname "$POSTGRES_DB" <<'SQL'
CREATE EXTENSION IF NOT EXISTS vector;

CREATE ROLE forgejo
  LOGIN
  PASSWORD :'forgejo_password'
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  NOREPLICATION
  NOBYPASSRLS;

SELECT 'CREATE DATABASE forgejo OWNER forgejo'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'forgejo')\gexec

REVOKE ALL PRIVILEGES ON DATABASE forgejo FROM PUBLIC;
GRANT CONNECT, CREATE, TEMPORARY ON DATABASE forgejo TO forgejo;

REVOKE CONNECT, TEMPORARY ON DATABASE gernetix_runtime FROM PUBLIC;
REVOKE ALL PRIVILEGES ON DATABASE gernetix_runtime FROM forgejo;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM forgejo;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM forgejo;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM forgejo;
REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public FROM forgejo;

\connect forgejo
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO forgejo;
SQL
