[platformio]
default_envs = esp32_s3_usb_helper_flashbox

[env:esp32_s3_usb_helper_flashbox]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino, espidf
lib_ldf_mode = deep+
monitor_speed = 115200
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = partitions_16mb_flashbox.csv
board_build.cmake_extra_args =
  -DIDF_COMPONENT_MANAGER=1
build_flags =
  -DGERNETIX_FLASHBOX_FIRMWARE_VERSION=\"0.1.0-dev\"
  -DGERNETIX_FLASHBOX_HARDWARE_PROFILE_ID=\"hardware.flashbox.esp32_s3_usb_helper\"
  -DGERNETIX_FLASHBOX_DISPLAY_ENABLED=0
  -DGERNETIX_FLASHBOX_DISPLAY_DRIVER_ILI9341=0
  -DGERNETIX_FLASHBOX_USB_OTG_DETECTION_ENABLED=1
  -DBOARD_HAS_PSRAM
lib_extra_dirs =
  ../shared
