export function createLcrMeterLab() {
  const state = { component: "capacitor", value: 1e-6, frequency: 1000, seriesResistance: .5 };
  return {
    id: "lcr", title: "LCR-Meter", status: "Nutzbar · Lernmodell", summary: "R, L, C, Impedanz und Phase",
    mount(target) {
      target.innerHTML = `<article class="lab-card"><h2>LCR-Meter</h2><p>Miss idealisierte Widerstände, Kondensatoren und Spulen bei verschiedenen Prüffrequenzen. Das Instrument zeigt Wert, Impedanz und Phasenlage.</p><div class="instrument-layout"><section><div class="lcr-display"><span data-symbol></span><strong data-primary></strong><small data-secondary></small></div><div class="impedance-vector" data-vector aria-label="Impedanzzeiger"></div><p class="scope-note" data-feedback></p></section><aside class="scope-controls" data-controls></aside></div></article>`;
      const symbol = target.querySelector("[data-symbol]"); const primary = target.querySelector("[data-primary]"); const secondary = target.querySelector("[data-secondary]"); const vector = target.querySelector("[data-vector]"); const feedback = target.querySelector("[data-feedback]"); const controls = target.querySelector("[data-controls]");
      const render = () => { const impedance = calculate(state); symbol.textContent = state.component === "resistor" ? "R" : state.component === "capacitor" ? "C" : "L"; primary.textContent = formatComponent(state.component, state.value); secondary.textContent = `|Z| ${formatOhms(impedance.magnitude)} · Phase ${impedance.phase.toFixed(1)}° · ${formatFrequency(state.frequency)}`; vector.innerHTML = `<div class="vector-axis"></div><div class="vector-arrow" style="--angle:${-impedance.phase}deg;--length:${Math.min(95, 30 + Math.log10(Math.max(1, impedance.magnitude)) * 18)}%"></div>`; feedback.textContent = state.component === "capacitor" ? "Bei höherer Frequenz sinkt der kapazitive Blindwiderstand; der Strom eilt der Spannung voraus." : state.component === "inductor" ? "Bei höherer Frequenz steigt der induktive Blindwiderstand; der Strom folgt der Spannung." : "Ein idealer Widerstand bleibt frequenzunabhängig und besitzt nahezu 0° Phasenverschiebung."; };
      addSelect(controls, "Bauteil", [["resistor", "Widerstand"], ["capacitor", "Kondensator"], ["inductor", "Spule"]], state.component, (value) => { state.component = value; state.value = value === "resistor" ? 1000 : value === "capacitor" ? 1e-6 : .01; }, render);
      addNumber(controls, "Bauteilwert (R Ω / C F / L H)", state.value, (value) => state.value = clamp(value, 1e-12, 1e9), "", render, .000001);
      addNumber(controls, "Prüffrequenz", state.frequency, (value) => state.frequency = clamp(value, 10, 1e6), "Hz", render, 10);
      addNumber(controls, "Serienverlust", state.seriesResistance, (value) => state.seriesResistance = clamp(value, 0, 1000), "Ω", render, .1);
      render();
    }, dispose() {},
  };
}
function calculate(state) { const omega = 2 * Math.PI * state.frequency; let reactance = 0; let resistance = state.seriesResistance; if (state.component === "resistor") resistance += state.value; if (state.component === "capacitor") reactance = -1 / (omega * state.value); if (state.component === "inductor") reactance = omega * state.value; return { magnitude: Math.hypot(resistance, reactance), phase: Math.atan2(reactance, resistance) * 180 / Math.PI }; }
function formatComponent(type, value) { if (type === "resistor") return formatOhms(value); if (type === "capacitor") { if (value < 1e-9) return `${(value * 1e12).toFixed(1)} pF`; if (value < 1e-6) return `${(value * 1e9).toFixed(1)} nF`; return `${(value * 1e6).toFixed(2)} µF`; } if (value < 1e-3) return `${(value * 1e6).toFixed(1)} µH`; if (value < 1) return `${(value * 1e3).toFixed(1)} mH`; return `${value.toFixed(2)} H`; }
function formatOhms(value) { if (value >= 1e6) return `${(value / 1e6).toFixed(2)} MΩ`; if (value >= 1000) return `${(value / 1000).toFixed(2)} kΩ`; return `${value.toFixed(2)} Ω`; }
function formatFrequency(value) { return value >= 1000 ? `${(value / 1000).toFixed(2)} kHz` : `${value.toFixed(0)} Hz`; }
function control(label) { const section = document.createElement("section"); section.className = "control-group"; section.innerHTML = `<h3>${label}</h3>`; return section; }
function addNumber(parent, label, initial, set, unit, changed, step) { const section = control(label); const input = document.createElement("input"); input.type = "number"; input.setAttribute("aria-label", label); input.value = initial; input.step = step; input.addEventListener("input", () => { set(Number(input.value)); changed(); }); const output = document.createElement("output"); output.textContent = unit; section.append(input, output); parent.append(section); }
function addSelect(parent, label, options, initial, set, changed) { const section = control(label); const select = document.createElement("select"); select.setAttribute("aria-label", label); for (const [value, text] of options) select.add(new Option(text, value)); select.value = initial; select.addEventListener("change", () => { set(select.value); changed(); }); section.append(select); parent.append(section); }
function clamp(value, min, max) { return Math.max(min, Math.min(max, Number.isFinite(value) ? value : min)); }
