#include "gernetix_flashbox_mqtt_job_client.h"
#include <Preferences.h>
#include <esp_event.h>
#include <mqtt_client.h>
#include <WiFi.h>
#include "gernetix/runtime_core.h"
#include "gernetix_flashbox_config.h"
#include "gernetix_flashbox_json_response.h"
namespace {
Preferences preferences; esp_mqtt_client_handle_t client = nullptr; String deviceId, broker, certificate, privateKey, topic;
FlashboxMqttJobClientStatus state = { "waiting_for_certificate", "", "", "", false, false };
String jsonString(const String& json, const char* key) { const String marker=String("\"")+key+"\""; int keyAt=json.indexOf(marker),colon=keyAt<0?-1:json.indexOf(':',keyAt+marker.length()),start=colon<0?-1:json.indexOf('"',colon+1); if(start<0)return ""; String value; bool escaping=false; for(int i=start+1;i<json.length();i++){char c=json.charAt(i);if(escaping){value+=c=='n'?'\n':c;escaping=false;continue;}if(c=='\\'){escaping=true;continue;}if(c=='"')return value;value+=c;}return ""; }
void publishStatus(const char* status,const String& jobId="") { if(!client||!state.connected)return; String payload="{\"device_id\":\""+deviceId+"\",\"flashbox_job_id\":\""+jobId+"\",\"status\":\""+status+"\"}"; String statusTopic="gernetix/devices/"+deviceId+"/status/flashbox"; esp_mqtt_client_publish(client,statusTopic.c_str(),payload.c_str(),0,1,0); }
esp_err_t onMqttEvent(esp_mqtt_event_handle_t event) { const int eventId=event->event_id; if(eventId==MQTT_EVENT_CONNECTED){state.connected=true;state.state="connected";esp_mqtt_client_subscribe(client,topic.c_str(),1);publishStatus("flashbox_online");}else if(eventId==MQTT_EVENT_DISCONNECTED){state.connected=false;state.state="disconnected";}else if(eventId==MQTT_EVENT_DATA){String incomingTopic(event->topic,event->topic_len),payload(event->data,event->data_len);if(incomingTopic!=topic)return ESP_OK;String jobId=jsonString(payload,"flashbox_job_id"),signature=jsonString(payload,"signature"),firmwareUrl=jsonString(payload,"firmware_url");if(jobId.length()==0||signature.length()==0||!firmwareUrl.startsWith("https://")){state.state="job_rejected";state.lastError="invalid_signed_job_contract";publishStatus("job_rejected",jobId);return ESP_OK;}state.lastJobId=jobId;state.state="job_received";state.lastError="";publishStatus("job_received",jobId);}else if(eventId==MQTT_EVENT_ERROR){state.state="error";state.lastError="mqtt_transport_error";} return ESP_OK; }
bool loadCredentials(){preferences.begin("gnx-prov",true);deviceId=preferences.getString("device_id","");broker=preferences.getString("mqtt_broker","");certificate=preferences.getString("mqtt_cert","");privateKey=preferences.getString("p256_key","");preferences.end();state.certificateConfigured=deviceId.length()>0&&certificate.length()>0&&privateKey.length()>0;topic=deviceId.length()?"gernetix/devices/"+deviceId+"/flashbox/jobs":"";state.topic=topic;return state.certificateConfigured&&broker.startsWith("mqtts://");}
void startClient(){esp_mqtt_client_config_t config={};config.uri=broker.c_str();config.client_id=deviceId.c_str();config.cert_pem=GERNETIX_FLASHBOX_HTTPS_ROOT_CA_PEM;config.client_cert_pem=certificate.c_str();config.client_key_pem=privateKey.c_str();config.event_handle=onMqttEvent;client=esp_mqtt_client_init(&config);if(!client||esp_mqtt_client_start(client)!=ESP_OK){state.state="error";state.lastError="mqtt_client_start_failed";return;}state.state="connecting";}
}
void flashboxMqttJobClientBegin(){loadCredentials();}
void flashboxMqttJobClientLoop(){if(client||WiFi.status()!=WL_CONNECTED)return;if(!loadCredentials()){state.state=state.certificateConfigured?"invalid_mqtts_endpoint":"waiting_for_certificate";return;}startClient();}
FlashboxMqttJobClientStatus flashboxMqttJobClientStatus(){return state;}
String flashboxMqttJobClientStatusJson(){gernetix::runtime::JsonWriter writer=flashboxJsonResponseWriter();gernetix::runtime::jsonBegin(writer);gernetix::runtime::jsonAppendString(writer,"state",state.state.c_str());gernetix::runtime::jsonAppendString(writer,"topic",state.topic.c_str());gernetix::runtime::jsonAppendString(writer,"last_job_id",state.lastJobId.c_str());gernetix::runtime::jsonAppendString(writer,"error",state.lastError.c_str());gernetix::runtime::jsonAppendBool(writer,"certificate_configured",state.certificateConfigured);gernetix::runtime::jsonAppendBool(writer,"connected",state.connected);gernetix::runtime::jsonEnd(writer);return flashboxJsonResponseString();}
