[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200

[env:esp32dev]
platform = espressif32
board = esp32dev
build_flags = -D GERNETIX_RADAR_OUT_PIN=27

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
build_flags = -D GERNETIX_RADAR_OUT_PIN=2

[env:nanoatmega328new]
platform = atmelavr
board = nanoatmega328new
build_flags = -D GERNETIX_RADAR_OUT_PIN=2
