function defaultCatalogSeed() {
  return {
    capabilities: [
      capability("capability.processor_esp32", "ESP32 ProcessorBoard"),
      capability("capability.processor_esp8266", "ESP8266 ProcessorBoard"),
      capability("capability.processor_avr_8bit", "AVR 8-bit ProcessorBoard"),
      capability("capability.processor_arduino_avr", "Arduino-kompatibles AVR-Board"),
      capability("capability.arduino_framework_runtime", "Arduino-Framework Runtime"),
      capability("capability.atmel_avr_bare_metal_runtime", "Atmel/AVR-nahe Runtime ohne Arduino"),
      capability("capability.usb_identification", "USB-Identifikation"),
      capability("capability.flash_firmware", "Firmware flashen"),
      capability("capability.usb_otg_host", "USB-OTG Host"),
      capability("capability.flashbox_target_flash", "Zielgeraete per Flashbox flashen"),
      capability("capability.flashbox_self_update", "Flashbox eigensicher aktualisieren"),
      capability("capability.flashbox_manifest_download", "Flashbox Manifest und Firmware laden"),
      capability("capability.basissoftware_supported", "GerNetiX-Basissoftware unterstuetzt"),
      capability("capability.device_http_status", "Device-HTTP-Status"),
      capability("capability.captive_setup_supported", "Captive Setup unterstuetzt"),
      capability("capability.wifi", "WiFi"),
      capability("capability.ota", "OTA"),
      capability("capability.display_output", "Display-Ausgabe"),
      capability("capability.touchscreen_input", "Touchscreen-Eingabe"),
      capability("capability.audio_output", "Audio-Ausgabe"),
      capability("capability.audio_input", "Audio-Eingabe"),
      capability("capability.camera_input", "Kamera-Eingabe"),
      capability("capability.bluetooth", "Bluetooth"),
      capability("capability.external_ram", "Externer RAM / PSRAM"),
      capability("capability.flash_storage", "Flash-Speicher"),
      capability("capability.removable_storage", "Wechselspeicher / Speicherkarte"),
      capability("capability.spi", "SPI"),
      capability("capability.rfid_reading", "RFID lesen"),
      capability("capability.item_identification", "Item Identification"),
      capability("capability.servo_control", "Servo-Steuerung"),
      capability("capability.mechanical_locking", "Mechanische Verriegelung"),
      capability("capability.fallback_unlock", "Fallback-Entriegelung"),
      capability("capability.digital_input", "Digitaler Eingang"),
      capability("capability.digital_output", "Digitaler Ausgang"),
      capability("capability.analog_input", "Analoger Eingang"),
      capability("capability.pulse_counter", "Impulszaehler"),
      capability("capability.quadrature_counter", "Inkrementalgeber A/B"),
      capability("capability.i2c", "I2C"),
      capability("capability.one_wire", "1-Wire"),
      capability("capability.uart", "UART"),
    ],
    hardwareItems: [
      ...boardFeatureOptions(),
      avrBoard({
        hardware_item_id: "hardware.processor_board.arduino_nano_r3_atmega328p",
        sku: "GNX-ARDUINO-NANO-R3-ATMEGA328P",
        title: "Arduino Nano R3 / ATmega328P",
        summary: "Arduino-Nano-R3-kompatibles AVR-Board fuer experimentelle Browser-Web-Serial-Erkennung ohne lokale avrdude-Installation.",
        vendor: "Arduino",
        form_factor: "nano",
        mcu_variant: "ATmega328P",
      }),
      esp8266Board({
        hardware_item_id: "hardware.processor_board.wemos_d1_mini_esp12f",
        sku: "GNX-ESP8266-D1-MINI-ESP12F",
        title: "Wemos D1 mini / ESP-12F",
        summary: "Gueltiger Einstieg fuer guenstige WLAN-Nodes mit ESP8266EX im ESP-12F Modul.",
        vendor: "Wemos",
        module_name: "ESP-12F",
      }),
      esp8266Board({
        hardware_item_id: "hardware.processor_board.generic_esp8266_esp12f",
        sku: "GNX-ESP8266-ESP12F-GENERIC",
        title: "Generisches ESP8266-Board mit ESP-12F Modul",
        summary: "Neutrale Katalogklasse fuer verbreitete ESP8266-Traegerboards mit ESP-12F Modul.",
        vendor: "Generic",
        module_name: "ESP-12F",
      }),
      esp8266Board({
        hardware_item_id: "hardware.processor_board.diymore_hw_364a_esp8266_oled",
        sku: "GNX-DIYMORE-HW-364A-ESP8266-OLED",
        title: "diymore HW-364A ESP8266 mit 0,96-Zoll-OLED",
        summary: "ESP8266-Entwicklungsboard HW-364A mit ESP-12F, integriertem 0,96-Zoll-SSD1306-OLED und USB-C-Anschluss.",
        vendor: "diymore",
        form_factor: "integrated_oled_display",
        module_name: "ESP-12F",
        usb_serial_chip: "CH340",
        cpu_architecture: "Xtensa 32-bit RISC",
        cpu_core: "Tensilica Xtensa LX106",
        clock_hz: 80000000,
        extra_capability_ids: ["capability.display_output", "capability.i2c"],
        factory_firmware_artifact: {
          artifact_id: "firmware_artifact.esp8266_diymore_hw364a_basissoftware_factory.latest",
          source: "sqlite",
          uri: "sqlite://provisioning_firmware_artifacts/firmware_artifact.esp8266_diymore_hw364a_basissoftware_factory.latest",
          version: "0.1.0",
          sha256: "",
        },
        platformio_build: {
          platform: "espressif8266",
          board: "nodemcuv2",
          environment: "diymore_hw_364a",
          framework: "arduino",
          supported_frameworks: ["arduino"],
          monitor_speed: 115200,
          upload_protocol: "esptool",
          flash_size_mb: 4,
          libraries: ["olikraus/U8g2@^2.36.17"],
          firmware_basis_id: "",
        },
        pin_profile: {
          analog_inputs: ["A0"],
          digital_pins: ["D0 / GPIO16", "D1 / GPIO5", "D2 / GPIO4", "D3 / GPIO0", "D4 / GPIO2", "D7 / GPIO13", "D8 / GPIO15", "RX / GPIO3", "TX / GPIO1"],
          pwm_pins: ["D1 / GPIO5", "D2 / GPIO4", "D3 / GPIO0", "D4 / GPIO2", "D7 / GPIO13", "D8 / GPIO15"],
          i2c: ["OLED: SDA D6 / GPIO14 + SCL D5 / GPIO12"],
          assigned_pins: {
            display_i2c: { sda: 14, scl: 12 },
          },
          diagnostic_output_allowlist: ["GPIO4", "GPIO5", "GPIO13"],
          diagnostic_note: "GPIO12 und GPIO14 sind fest mit dem OLED verbunden. GPIO0, GPIO2 und GPIO15 beeinflussen den Bootmodus; GPIO1 und GPIO3 sind fuer UART belegt.",
        },
        default_instance_configuration: {
          board_model: "HW-364A",
          verification_status: "user_reference",
          board_features: {
            display: {
              enabled: true,
              hardware: "oled",
              driver: "ssd1306",
              connection: "i2c",
              address: "0x3C",
              diagonal_in: 0.96,
              width: 128,
              height: 64,
              verification_status: "user_reference",
            },
            flash: { enabled: true, hardware: "qspi_flash", value: "4_mb" },
            ram: { enabled: true, hardware: "internal_sram", value: "64_kb", verification_status: "user_confirmed" },
            wifi: { enabled: true, hardware: "2_4_ghz", driver: "arduino_wifi" },
          },
        },
        verification_status: "user_reference",
        evidence: {
          source_type: "user_supplied_product_pinout_and_specifications",
          source_reference: "diymore HW-364A ESP8266 OLED pinout and confirmed hardware data",
        },
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.generic_esp_wroom32",
        sku: "GNX-ESP32-WROOM32-GENERIC",
        title: "Generisches ESP32-Board mit ESP-WROOM-32 Modul",
        summary: "Neutrale Katalogklasse fuer ESP32-Traegerboards mit ESP-WROOM-32 Modul.",
        module_name: "ESP-WROOM-32",
        mcu_variant: "ESP32",
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.esp32_2432s028",
        sku: "GNX-ESP32-2432S028",
        title: "ESP32-2432S028 2,8-Zoll-Touchdisplay",
        summary: "Community-Board mit ESP32-WROOM-32, 2,8-Zoll-ILI9341-Display und XPT2046-Resistivtouch; keine ESP32-S3-Variante.",
        vendor: "Generic",
        form_factor: "integrated_touch_display",
        module_name: "ESP-WROOM-32",
        mcu_variant: "ESP32",
        extra_capability_ids: ["capability.display_output", "capability.touchscreen_input", "capability.spi"],
        pin_profile: {
          assigned_pins: {
            display_spi: { mosi: 13, miso: 12, sclk: 14, cs: 15, dc: 2, reset: -1, backlight: 21 },
            touch_spi: { cs: 33, mosi: 13, miso: 12, sclk: 14 },
          },
          diagnostic_output_allowlist: [],
          diagnostic_note: "GPIO2 ist als Display-DC belegt und kann den Bootvorgang beeinflussen. Display und Touch teilen sich SPI; keine belegten Pins als Testausgang verwenden.",
        },
        platformio_build: {
          platform: "espressif32",
          board: "esp32dev",
          environment: "esp32-2432s028-ili9341",
          framework: "arduino",
          supported_frameworks: ["arduino"],
          monitor_speed: 115200,
          upload_protocol: "esptool",
          flash_size_mb: 4,
          libraries: ["bodmer/TFT_eSPI@^2.5.43", "paulstoffregen/XPT2046_Touchscreen@^1.4"],
          firmware_basis_id: "",
        },
        default_instance_configuration: {
          board_model: "ESP32-2432S028",
          verification_status: "user_reference",
          hardware_test_status: "pending_controller_and_pinout_check",
          board_features: {
            display: {
              enabled: true,
              hardware: "tft_lcd",
              driver: "ili9341",
              connection: "spi",
              width: 320,
              height: 240,
              pins: { mosi: 13, miso: 12, sclk: 14, cs: 15, dc: 2, reset: -1, backlight: 21 },
              verification_status: "user_reference",
            },
            touch: {
              enabled: true,
              hardware: "resistiv",
              driver: "xpt2046",
              connection: "spi",
              pins: { cs: 33, mosi: 13, miso: 12, sclk: 14 },
              verification_status: "user_reference",
            },
            flash: { enabled: true, hardware: "qspi_flash", value: "4_mb", verification_status: "user_reference" },
            ram: { enabled: true, hardware: "internal_sram", value: "520_kb", verification_status: "processor_specification" },
            wifi: { enabled: true, hardware: "2_4_ghz", driver: "arduino_wifi", verification_status: "processor_specification" },
          },
        },
        verification_status: "user_reference",
        evidence: {
          source_type: "project_firmware_and_community_board_reference",
          source_reference: "GerNetiX-Projekte/esp-kvm; vor Flashen Controlleraufdruck und Pinout am konkreten Board prüfen",
        },
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.espressif_esp32_devkitc",
        sku: "GNX-ESP32-DEVKITC",
        title: "Espressif ESP32-DevKitC",
        summary: "Offizielles Espressif-Development-Board fuer ESP32-WROOM-Module.",
        vendor: "Espressif",
        module_name: "ESP-WROOM-32",
        mcu_variant: "ESP32",
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.ai_thinker_esp32_cam",
        sku: "GNX-ESP32-CAM-AI-THINKER-OV2640",
        title: "AI-Thinker ESP32-CAM mit OV2640",
        summary: "Verbreitetes ESP32-Kameraboard mit OV2640, 4 MB Flash und PSRAM für JPEG-Aufnahme und lokale MJPEG-Lernprojekte.",
        vendor: "AI-Thinker",
        form_factor: "integrated_camera",
        module_name: "ESP32-S",
        mcu_variant: "ESP32",
        extra_capability_ids: ["capability.camera_input", "capability.external_ram"],
        pin_profile: {
          assigned_pins: {
            camera_parallel: {
              pwdn: 32, reset: -1, xclk: 0, sccb_sda: 26, sccb_scl: 27,
              d0: 5, d1: 18, d2: 19, d3: 21, d4: 36, d5: 39, d6: 34, d7: 35,
              vsync: 25, href: 23, pclk: 22,
            },
          },
          diagnostic_output_allowlist: ["GPIO4"],
          diagnostic_note: "Die Kamerasignale sind fest verdrahtet. GPIO4 ist häufig zugleich Blitz-LED bzw. microSD-Datenleitung und daher nur kontextabhängig frei.",
        },
        default_instance_configuration: {
          board_model: "AI-Thinker ESP32-CAM",
          verification_status: "vendor_reference",
          board_features: {
            camera: {
              enabled: true,
              hardware: "ov2640",
              driver: "espressif_esp32_camera",
              connection: "parallel_dvp_sccb",
              pixel_format: "jpeg",
              verification_status: "vendor_reference",
            },
            psram: {
              enabled: true,
              hardware: "qspi_psram",
              driver: "esp_idf_heap_psram",
              value: "4_mb",
              verification_status: "vendor_reference",
            },
            flash: {
              enabled: true,
              hardware: "qspi_flash",
              driver: "esp_idf_partition_table",
              value: "4_mb",
              verification_status: "vendor_reference",
            },
          },
        },
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.arduino_nano_esp32",
        sku: "GNX-ARDUINO-NANO-ESP32",
        title: "Arduino Nano ESP32",
        summary: "Offizielles Arduino-Nano-Board mit ESP32-S3-basierter NORA-W106 Realisierung.",
        vendor: "Arduino",
        form_factor: "nano",
        module_name: "NORA-W106",
        mcu_variant: "ESP32-S3",
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.generic_esp32_s3_wroom1",
        sku: "GNX-ESP32-S3-WROOM1-GENERIC",
        title: "Generisches ESP32-S3-Board mit ESP32-S3-WROOM-1 Modul",
        summary: "Neutrale Katalogklasse fuer ESP32-S3-Traegerboards mit ESP32-S3-WROOM-1 Modul.",
        module_name: "ESP32-S3-WROOM-1",
        mcu_variant: "ESP32-S3",
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.espressif_esp32_s3_devkitc_1",
        sku: "GNX-ESP32-S3-DEVKITC-1",
        title: "Espressif ESP32-S3-DevKitC-1",
        summary: "Offizielles Espressif-Development-Board fuer ESP32-S3-WROOM-Module.",
        vendor: "Espressif",
        module_name: "ESP32-S3-WROOM-1",
        mcu_variant: "ESP32-S3",
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.generic_esp32_s3_touch_display",
        sku: "GNX-ESP32-S3-TOUCH-DISPLAY-GENERIC",
        title: "Generisches ESP32-S3 Touch-Display-Board",
        summary: "Katalogklasse fuer ESP32-S3-Boards mit integriertem Display und Touchcontroller.",
        form_factor: "integrated_touch_display",
        module_name: "ESP32-S3-WROOM-1",
        mcu_variant: "ESP32-S3",
        extra_capability_ids: ["capability.display_output", "capability.touchscreen_input"],
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.esp32_s3_es3c28p",
        sku: "GNX-ESP32-S3-ES3C28P",
        title: "ESP32-S3 ES3C28P Touch-Board",
        summary: "Lokal getestetes ESP32-S3-Board mit 2,8-Zoll-ILI9341V-Display, FT6336G-Touch und ES8311/NS8002E-Audio.",
        vendor: "ES3C28P",
        form_factor: "integrated_touch_display_audio",
        mcu_variant: "ESP32-S3",
        module_name: "ESP32-S3-WROOM-1",
        module_memory_variant: "N16R8",
        firmware_build_target_id: "firmware_build_target.esp32_s3_opi_n16r8",
        extra_capability_ids: ["capability.display_output", "capability.touchscreen_input", "capability.audio_output", "capability.bluetooth", "capability.analog_input"],
        pin_profile: {
          assigned_pins: {
            display_spi: { mosi: 11, miso: 13, sclk: 12, cs: 10, dc: 46, reset: -1, backlight: 45 },
            touch_i2c: { sda: 16, scl: 15, interrupt: 17, reset: 18 },
            audio_i2s: { enable: 1, mclk: 4, bclk: 5, data_out: 8, lrclk: 7 },
            battery_adc: { pin: 9, voltage_divider: 2.0 },
          },
          diagnostic_output_allowlist: [],
          diagnostic_note: "Keine Onboard-LED dokumentiert; belegte Pins duerfen nicht generisch als Testausgang verwendet werden.",
        },
        default_instance_configuration: {
          board_model: "ESP32-S3 ES3C28P",
          verification_status: "user_tested",
          evidence: {
            source_type: "working_platformio_project",
            source_reference: "ESP32-OLED-Games/AI-Assistant-ESP32-Touch",
          },
          board_features: {
            display: {
              enabled: true,
              hardware: "tft_lcd",
              driver: "ili9341",
              connection: "spi",
              controller_variant: "ILI9341V",
              width: 240,
              height: 320,
              pins: { mosi: 11, miso: 13, sclk: 12, cs: 10, dc: 46, reset: -1, backlight: 45 },
              verification_status: "user_tested",
            },
            touch: {
              enabled: true,
              hardware: "kapazitiv",
              driver: "ft6336g",
              connection: "i2c",
              address: "0x38",
              clock_hz: 400000,
              pins: { sda: 16, scl: 15, interrupt: 17, reset: 18 },
              verification_status: "user_tested",
            },
            speaker: {
              enabled: true,
              hardware: "i2s_verst_rker",
              driver: "es8311",
              connection: "i2s",
              codec_address: "0x18",
              amplifier: "NS8002E",
              format: "philips_i2s",
              pins: { enable: 1, mclk: 4, bclk: 5, data_out: 8, lrclk: 7 },
              verification_status: "user_tested",
            },
            bluetooth: {
              enabled: true,
              hardware: "bluetooth_low_energy",
              connection: "im_prozessor_integriert",
              verification_status: "processor_specification",
            },
            wifi: {
              enabled: true,
              hardware: "2_4_ghz",
              driver: "arduino_wifi",
              verification_status: "user_tested",
            },
            ram: {
              enabled: true,
              hardware: "interner_sram",
              driver: "esp_idf_heap",
              connection: "im_modul_integriert",
              value: "512_kb",
              verification_status: "user_confirmed",
            },
            psram: {
              enabled: true,
              hardware: "octal_psram",
              driver: "esp_idf_heap_psram",
              connection: "im_modul_integriert",
              value: "8_mb",
              verification_status: "module_variant_confirmed",
            },
            flash: {
              enabled: true,
              hardware: "qspi_flash",
              driver: "esp_idf_partition_table",
              connection: "extern_auf_dem_board",
              value: "16_mb",
              verification_status: "user_confirmed",
            },
          },
          battery_measurement: {
            enabled: true,
            connection: "adc",
            pin: 9,
            voltage_divider: 2.0,
            verification_status: "user_tested",
          },
          datasheet_url: "",
          datasheet_required: true,
        },
        verification_status: "locally_verified",
        evidence: {
          source_type: "working_platformio_project",
          source_reference: "ESP32-OLED-Games/AI-Assistant-ESP32-Touch",
        },
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.waveshare_esp32_s3_cam_ov3660",
        sku: "GNX-WAVESHARE-ESP32-S3-CAM-OV3660",
        title: "Waveshare ESP32-S3-CAM-OV3660",
        summary: "Waveshare-Kameraboard mit ESP32-S3R8, OV3660, 16 MB Flash, 8 MB PSRAM, Dual-Mikrofon, Audioausgang und TF-Kartenslot.",
        vendor: "Waveshare",
        form_factor: "integrated_camera_audio",
        mcu_variant: "ESP32-S3",
        module_name: "ESP32-S3R8",
        module_memory_variant: "N16R8",
        firmware_build_target_id: "firmware_build_target.esp32_s3_opi_n16r8",
        extra_capability_ids: [
          "capability.camera_input", "capability.external_ram", "capability.audio_input",
          "capability.audio_output", "capability.removable_storage", "capability.bluetooth",
          "capability.i2c", "capability.spi", "capability.uart",
        ],
        pin_profile: {
          assigned_pins: {
            camera_parallel_dvp_sccb: {
              pwdn: -1, reset: -1, xclk: 38, sccb_sda: 8, sccb_scl: 7,
              d0: 45, d1: 47, d2: 48, d3: 46, d4: 42, d5: 40, d6: 39, d7: 21,
              vsync: 17, href: 18, pclk: 41,
            },
            microphone_i2s: { mclk: 10, bclk: 11, lrclk: 12, data_in: 13, data_out: 14, sda: 8, scl: 7 },
            speaker_i2s: { mclk: 10, bclk: 11, lrclk: 12, data_in: 13, data_out: 14, sda: 8, scl: 7 },
            storage_sdmmc: { clk: 16, cmd: 43, d0: 44 },
            display_spi_qspi: { cs: 6, sclk: 5, sda3: 4, dc_sda2: 3, miso_sda1: 2, mosi_sda0: 1 },
            touch_i2c: { scl: 7, sda: 8, interrupt: 9 },
            header_i2c: { scl: 7, sda: 8 },
            header_uart: { tx: 43, rx: 44 },
          },
          diagnostic_output_allowlist: [],
          shared_pin_notes: [
            "GPIO7/GPIO8 werden fuer Kamera-SCCB, Audio-I2C, Touch-I2C und den externen I2C-Anschluss gemeinsam genutzt.",
            "GPIO43/GPIO44 werden sowohl fuer SDMMC als auch am UART-Anschluss verwendet und duerfen nicht konfliktfrei gleichzeitig vorausgesetzt werden.",
          ],
          diagnostic_note: "Kamera, Audio, TF-Karte, LCD/Touch-Anschluss und der CH32V003-I/O-Expander belegen einen grossen Teil der GPIOs. Keine undokumentierten Pins als generischen Testausgang verwenden.",
        },
        default_instance_configuration: {
          board_model: "Waveshare ESP32-S3-CAM-OV3660",
          product_family: "Waveshare ESP32-S3-CAM-OVxxxx",
          available_camera_variants: ["OV5640", "OV3660", "GC2145", "GC0308"],
          verification_status: "vendor_reference",
          evidence: {
            source_type: "manufacturer_documentation_and_examples",
            product_url: "https://www.waveshare.com/esp32-s3-cam-ov5640.htm",
            documentation_url: "https://docs.waveshare.com/ESP32-S3-CAM-OVxxxx/Instructions-For-Use",
            example_repository_url: "https://github.com/waveshareteam/ESP32-S3-CAM-OVxxxx",
            schematic_url: "https://files.waveshare.com/wiki/ESP32-S3-CAM-OVxxxx/ESP32-S3-CAM-XXXX-schematic.pdf",
          },
          board_features: {
            camera: {
              enabled: true,
              hardware: "ov3660",
              driver: "espressif_esp32_camera",
              connection: "parallel_dvp_sccb",
              pixel_formats: ["jpeg", "rgb565", "yuv", "raw_rgb"],
              maximum_resolution: "2048x1536",
              xclk_hz: 20000000,
              verification_status: "vendor_reference",
            },
            camera_power: {
              enabled: true,
              hardware: "CH32V003F4U6",
              driver: "waveshare_io_extension",
              connection: "i2c_io_expander",
              value: "0x24",
              pins: { sda: 8, scl: 7, address: 0x24, output: 6 },
              verification_status: "vendor_reference",
            },
            microphone: {
              enabled: true,
              hardware: "dual_microphone_array",
              driver: "es7210",
              connection: "i2s",
              codec_address: "0x40",
              pins: { mclk: 10, bclk: 11, lrclk: 12, data_in: 13, sda: 8, scl: 7 },
              verification_status: "vendor_reference",
            },
            speaker: {
              enabled: true,
              hardware: "audio_codec_amplifier",
              driver: "es8311",
              connection: "i2s",
              amplifier: "NS4150B",
              pins: { mclk: 10, bclk: 11, lrclk: 12, data_out: 14, sda: 8, scl: 7 },
              verification_status: "vendor_reference",
            },
            storage: {
              enabled: true,
              hardware: "tf_microsd_slot",
              driver: "sd_mmc",
              connection: "sdmmc",
              bus_width: 1,
              verification_status: "vendor_reference",
            },
            display: {
              enabled: false,
              included: false,
              optional_external_hardware: true,
              hardware: "external_spi_qspi_lcd",
              driver: "depends_on_attached_display",
              connection: "spi_qspi",
              connector: "18_pin_fpc",
              supported_display_sizes_inch: [1.83, 2.0, 2.8, 3.5],
              verification_status: "vendor_reference",
            },
            touch: {
              enabled: false,
              included: false,
              optional_external_hardware: true,
              hardware: "external_touch_controller",
              driver: "depends_on_attached_display",
              connection: "i2c",
              connector: "shared_18_pin_lcd_fpc",
              verification_status: "vendor_reference",
            },
            bluetooth: {
              enabled: true,
              hardware: "bluetooth_low_energy",
              connection: "im_prozessor_integriert",
              verification_status: "processor_specification",
            },
            wifi: {
              enabled: true,
              hardware: "2_4_ghz",
              driver: "arduino_wifi",
              connection: "pcb_antenne",
              verification_status: "vendor_reference",
            },
            ram: {
              enabled: true,
              hardware: "interner_sram",
              driver: "esp_idf_heap",
              connection: "im_prozessor_integriert",
              value: "512_kb",
              verification_status: "processor_specification",
            },
            psram: {
              enabled: true,
              hardware: "octal_psram",
              driver: "esp_idf_heap_psram",
              connection: "im_prozessor_integriert",
              value: "8_mb",
              verification_status: "vendor_reference",
            },
            flash: {
              enabled: true,
              hardware: "qspi_flash",
              driver: "arduino_partition_scheme",
              connection: "extern_auf_dem_board",
              value: "16_mb",
              recommended_partition_scheme: "16M Flash (3MB APP/9.9MB FATFS)",
              verification_status: "vendor_reference",
            },
          },
          io_expander: {
            hardware: "CH32V003F4U6",
            roles: ["camera_enable", "display_reset", "touch_reset", "display_backlight", "tf_card_chip_select", "usb_can_select"],
            lines: {
              exio0: "unused",
              exio1: "touch_reset",
              exio2: "display_backlight",
              exio3: "display_reset",
              exio4: "tf_card_chip_select",
              exio5: "usb_can_select",
              exio6: "camera_enable",
              exio7: "unused",
              exio_pwm: "display_backlight_pwm",
            },
            verification_status: "vendor_reference",
          },
          external_connectors: {
            camera: { type: "24_pin_fpc", interface: "parallel_dvp_sccb" },
            display: { type: "18_pin_fpc", interfaces: ["spi", "qspi"], includes_touch_signals: true },
            i2c: { pins: { gnd: "GND", power: "3V3", sda: 8, scl: 7 } },
            uart: { pins: { gnd: "GND", power: "3V3", tx: 43, rx: 44 } },
            speaker: { type: "2_pin_header", interface: "amplified_analog_audio" },
            battery: {
              type: "2_pin_1_25_mm_connector",
              battery_type: "single_cell_lithium",
              nominal_voltage_v: 3.7,
              charging_supported: true,
            },
          },
          mechanical: {
            width_mm: 37.0,
            height_mm: 37.0,
            mounting_hole_center_spacing_x_mm: 32.6,
            mounting_hole_center_spacing_y_mm: 32.6,
            mounting_hole_radius_mm: 2.25,
            mounting_hole_center_to_edge_mm: 2.2,
            verification_status: "vendor_reference",
          },
        },
        platformio_build: {
          platform: "espressif32",
          board: "esp32-s3-devkitc-1",
          environment: "waveshare_esp32_s3_cam_ov3660",
          framework: "arduino",
          monitor_speed: 115200,
          upload_protocol: "esptool",
          flash_size_mb: 16,
          supported_frameworks: ["arduino", "espidf"],
          build_flags: [
            "-D ARDUINO_USB_MODE=1", "-D ARDUINO_USB_CDC_ON_BOOT=1",
            "-D BOARD_HAS_PSRAM", "-D CAMERA_MODEL_ESP_EYE",
          ],
          platformio_options: { "board_build.arduino.memory_type": "qio_opi" },
          firmware_basis_id: "",
        },
        verification_status: "vendor_reference",
        evidence: {
          source_type: "manufacturer_documentation_and_examples",
          source_reference: "Waveshare ESP32-S3-CAM-OVxxxx",
        },
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.waveshare_esp32_s3_audio_board",
        sku: "GNX-WAVESHARE-ESP32-S3-AUDIO-BOARD",
        title: "Waveshare ESP32-S3-AUDIO-Board",
        summary: "Waveshare AI-Smart-Speaker-Board mit ESP32-S3R8, 16 MB Flash, 8 MB PSRAM, ES7210-Doppelmikrofon, ES8311-Audioausgabe, sieben RGB-LEDs, RTC und TF-Kartenslot.",
        vendor: "Waveshare",
        form_factor: "integrated_audio_ai_speaker",
        mcu_variant: "ESP32-S3",
        module_name: "ESP32-S3R8",
        module_memory_variant: "N16R8",
        firmware_build_target_id: "firmware_build_target.esp32_s3_opi_n16r8",
        extra_capability_ids: [
          "capability.external_ram", "capability.audio_input", "capability.audio_output",
          "capability.removable_storage", "capability.bluetooth", "capability.i2c",
          "capability.spi",
        ],
        pin_profile: {
          assigned_pins: {
            microphone_i2s: { sda: 11, scl: 10, mclk: 12, bclk: 13, lrclk: 14, data_in: 15 },
            speaker_i2s: { sda: 11, scl: 10, mclk: 12, bclk: 13, lrclk: 14, data_out: 16 },
            rgb_led: { data: 38 },
            storage_spi: { miso: 41, mosi: 42, sclk: 40 },
            display_spi_qspi: { cs: 3, sclk: 4, backlight: 5, sda3: 6, dc_sda2: 7, miso_sda1: 8, mosi_sda0: 9 },
            touch_i2c: { scl: 10, sda: 11 },
            camera_parallel_dvp: {
              d0: 2, d1: 17, d2: 18, d3: 39, d4: 45, d5: 46, d6: 47, d7: 48,
              href: 1, pclk_primary: 44, pclk_alternate: 19, xclk_primary: 43, xclk_alternate: 20,
            },
            shared_i2c: { scl: 10, sda: 11 },
          },
          diagnostic_output_allowlist: [],
          shared_pin_notes: [
            "GPIO10/GPIO11 bilden den gemeinsamen I2C-Bus fuer ES7210, ES8311, Touch und weitere Boardfunktionen.",
            "GPIO12 bis GPIO16 sind fest dem gemeinsamen Audio-I2S-Bus zugeordnet.",
            "GPIO3 bis GPIO9 sind mit dem optionalen LCD-Anschluss geteilt; GPIO5 steuert dessen Hintergrundbeleuchtung.",
            "Die Kamera-Takte werden ueber den I/O-Expander zwischen GPIO43/GPIO44 und GPIO20/GPIO19 umgeschaltet.",
          ],
          diagnostic_note: "Audio, RGB-Ring, TF-Karte, LCD-/Touch- und Kameraanschluss belegen nahezu alle herausgefuehrten GPIOs. Keine Pins als generischen Diagnoseausgang verwenden.",
        },
        default_instance_configuration: {
          board_model: "ESP32-S3-AUDIO-Board",
          product_family: "Waveshare ESP32-S3-AUDIO-Board",
          manufacturer_skus: ["32184", "32185"],
          verification_status: "vendor_reference",
          hardware_test_status: "pending_user_hardware_test",
          evidence: {
            source_type: "manufacturer_documentation_and_schematic",
            product_url: "https://www.waveshare.com/esp32-s3-audio-board.htm",
            documentation_url: "https://docs.waveshare.com/ESP32-S3-AUDIO-Board",
            schematic_url: "https://files.waveshare.com/wiki/ESP32-S3-AUDIO-Board/ESP32-S3-AUDIO-Board-Schematic.pdf",
            retailer_url: "https://www.berrybase.de/waveshare-esp32-s3-ai-smart-speaker-development-board-dual-mikrofon-wifi-bt5-16mb-flash-240-mhz",
          },
          board_features: {
            buttons: {
              enabled: true,
              included: true,
              hardware: "function_buttons",
              driver: "gpio_input",
              connection: "gpio_via_io_expander",
              count: 3,
              verification_status: "manufacturer_schematic",
            },
            microphone: {
              enabled: true,
              included: true,
              hardware: "dual_microphone_array",
              driver: "es7210",
              connection: "i2s",
              codec_address: "0x40",
              channels: 2,
              capabilities: ["noise_reduction", "acoustic_echo_cancellation"],
              verification_status: "vendor_reference",
            },
            speaker: {
              enabled: true,
              included: false,
              optional_external_hardware: true,
              hardware: "audio_codec_amplifier",
              driver: "es8311",
              connection: "i2s",
              amplifier: "NS4150B",
              connector: "2_pin_1_25_mm",
              verification_status: "vendor_reference",
            },
            rgb_led: {
              enabled: true,
              included: true,
              hardware: "ws2812b_ring",
              driver: "esp_idf_led_strip",
              connection: "one_wire_led_data",
              count: 7,
              verification_status: "schematic_reference",
            },
            rtc: {
              enabled: true,
              included: true,
              hardware: "pcf85063",
              driver: "pcf85063",
              connection: "i2c",
              backup_battery_connector: true,
              verification_status: "vendor_reference",
            },
            storage: {
              enabled: true,
              included: true,
              hardware: "tf_microsd_slot",
              driver: "sd_spi",
              connection: "spi",
              chip_select: "EXIO3",
              verification_status: "vendor_reference",
            },
            display: {
              enabled: false,
              included: false,
              optional_external_hardware: true,
              hardware: "external_spi_qspi_lcd",
              driver: "depends_on_attached_display",
              connection: "spi_qspi",
              connector: "18_pin_fpc",
              supported_display_sizes_inch: [1.47, 2.0, 2.8, 3.5],
              reset: "EXIO0",
              verification_status: "vendor_reference",
            },
            touch: {
              enabled: false,
              included: false,
              optional_external_hardware: true,
              hardware: "external_touch_controller",
              driver: "depends_on_attached_display",
              connection: "i2c",
              connector: "shared_18_pin_lcd_fpc",
              reset: "EXIO1",
              interrupt: "EXIO2",
              verification_status: "vendor_reference",
            },
            camera: {
              enabled: false,
              included: false,
              optional_external_hardware: true,
              hardware: "external_dvp_camera",
              driver: "espressif_esp32_camera",
              connection: "parallel_dvp",
              connector: "24_pin_fpc",
              supported_sensors: ["OV2640", "OV5640"],
              power_down: "EXIO5",
              clock_route_select: "EXIO6",
              verification_status: "vendor_reference",
            },
            bluetooth: {
              enabled: true,
              hardware: "bluetooth_low_energy_5",
              connection: "im_prozessor_integriert",
              verification_status: "processor_specification",
            },
            wifi: {
              enabled: true,
              hardware: "2_4_ghz",
              driver: "esp_idf_wifi",
              connection: "pcb_antenne_ipex_option",
              verification_status: "vendor_reference",
            },
            ram: {
              enabled: true,
              hardware: "interner_sram",
              driver: "esp_idf_heap",
              connection: "im_prozessor_integriert",
              value: "512_kb",
              verification_status: "processor_specification",
            },
            psram: {
              enabled: true,
              hardware: "octal_psram",
              driver: "esp_idf_heap_psram",
              connection: "im_prozessor_integriert",
              value: "8_mb",
              verification_status: "vendor_reference",
            },
            flash: {
              enabled: true,
              hardware: "qspi_flash",
              driver: "esp_idf_partition_table",
              connection: "extern_auf_dem_board",
              value: "16_mb",
              verification_status: "vendor_reference",
            },
          },
          io_expander: {
            hardware: "TCA9555PWR",
            address: "0x20",
            roles: ["display_reset", "touch_reset", "touch_interrupt", "tf_card_chip_select", "camera_power_down", "camera_clock_route_select"],
            lines: {
              exio0: "display_reset",
              exio1: "touch_reset",
              exio2: "touch_interrupt",
              exio3: "tf_card_chip_select",
              exio5: "camera_power_down",
              exio6: "camera_clock_route_select",
              exio7: "usb_uart_camera_route_select",
            },
            verification_status: "manufacturer_schematic",
          },
          external_connectors: {
            camera: { type: "24_pin_fpc", interface: "parallel_dvp" },
            display: { type: "18_pin_fpc", interfaces: ["spi", "qspi"], includes_touch_signals: true },
            speaker: { type: "2_pin_1_25_mm", interface: "amplified_analog_audio" },
            battery: {
              type: "2_pin_mx1_25",
              battery_type: "single_cell_lithium",
              nominal_voltage_v: 3.7,
              charging_supported: true,
              battery_optional: true,
            },
            rtc_battery: { type: "rechargeable_rtc_battery_header" },
          },
        },
        platformio_build: {
          platform: "espressif32",
          board: "4d_systems_esp32s3_gen4_r8n16",
          environment: "waveshare_esp32_s3_audio_board",
          framework: "espidf",
          monitor_speed: 115200,
          upload_protocol: "esptool",
          flash_size_mb: 16,
          supported_frameworks: ["espidf", "arduino"],
          build_flags: ["-D BOARD_HAS_PSRAM"],
          firmware_basis_id: "gernetix-runtime-basissoftware",
          firmware_basis_version: "workspace",
          firmware_basis_variant: "full",
        },
        verification_status: "vendor_reference",
        evidence: {
          source_type: "manufacturer_documentation_and_schematic",
          source_reference: "Waveshare ESP32-S3-AUDIO-Board",
        },
      }),
      flashbox({
        hardware_item_id: "hardware.flashbox.esp32_s3_usb_helper",
        sku: "GNX-FLASHBOX-S3-USB-HELPER",
        title: "GerNetiX FlashBox ESP32-S3 USB Helper",
        summary: "Gekaufter, displayloser GerNetiX-Helper fuer FlashBox-Flash als dritter Flash-Weg neben USB und OTA.",
        vendor: "GerNetiX",
        form_factor: "displayless_dual_usb_helper",
        mcu_variant: "ESP32-S3",
        module_name: "ESP32-S3-WROOM-1",
        module_memory_variant: "N16R8",
      }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.generic_esp32_c6_wroom1",
        sku: "GNX-ESP32-C6-WROOM1-GENERIC",
        title: "Generisches ESP32-C6-Board mit ESP32-C6-WROOM-1 Modul",
        summary: "Neutrale Katalogklasse fuer ESP32-C6-Traegerboards mit ESP32-C6-WROOM-1 Modul.",
        module_name: "ESP32-C6-WROOM-1",
        mcu_variant: "ESP32-C6",
      }),
      sensor({ id: "pt1000", title: "PT1000 Widerstandsthermometer", measurements: ["temperature"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "ntc", title: "NTC-Temperatursensor", measurements: ["temperature"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "ptc", title: "PTC-Temperatursensor", measurements: ["temperature"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "ds18b20", title: "DS18B20 Temperatursensor", measurements: ["temperature"], signal: "one_wire", capabilities: ["capability.one_wire"] }),
      sensor({ id: "dht22", title: "DHT22 Temperatur- und Feuchtesensor", measurements: ["temperature", "humidity"], signal: "digital", capabilities: ["capability.digital_input"] }),
      sensor({ id: "bme280", title: "BME280 Temperatur-, Feuchte- und Drucksensor", measurements: ["temperature", "humidity", "pressure"], signal: "i2c", capabilities: ["capability.i2c"] }),
      sensor({ id: "soil_moisture_analog", title: "Kapazitiver Bodenfeuchtesensor", measurements: ["soil_moisture"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "ldr", title: "LDR Fotowiderstand", measurements: ["light"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "bh1750", title: "BH1750 Helligkeitssensor", measurements: ["light"], signal: "i2c", capabilities: ["capability.i2c"] }),
      sensor({ id: "hc_sr04", title: "HC-SR04 Ultraschall-Abstandssensor", measurements: ["distance"], signal: "pulse_counter", capabilities: ["capability.pulse_counter"] }),
      sensor({ id: "reed_contact", title: "Reedkontakt", measurements: ["contact"], signal: "digital", capabilities: ["capability.digital_input"] }),
      sensor({ id: "hall_a3144", title: "A3144 Hall-Schaltsensor", measurements: ["magnetic_field"], signal: "digital", capabilities: ["capability.digital_input"] }),
      sensor({ id: "hall_ss49e", title: "SS49E linearer Hallsensor", measurements: ["magnetic_field"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "incremental_encoder_ab", title: "Inkrementalgeber A/B", measurements: ["position", "rotation"], signal: "incremental_ab", capabilities: ["capability.quadrature_counter"] }),
      sensor({ id: "pulse_encoder", title: "Einspuriger Impulsgeber", measurements: ["rotation", "speed"], signal: "pulse_counter", capabilities: ["capability.pulse_counter"] }),
      sensor({ id: "adxl335", title: "ADXL335 Beschleunigungssensor", measurements: ["acceleration"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "adxl345", title: "ADXL345 Beschleunigungssensor", measurements: ["acceleration"], signal: "i2c", capabilities: ["capability.i2c"] }),
      sensor({ id: "mpu6050", title: "MPU6050 Beschleunigungs- und Drehratensensor", measurements: ["acceleration", "rotation"], signal: "i2c", capabilities: ["capability.i2c"] }),
      sensor({ id: "pir", title: "PIR-Bewegungssensor", measurements: ["motion"], signal: "digital", capabilities: ["capability.digital_input"] }),
      sensor({ id: "water_level_analog", title: "Analoger Wasserstandssensor", measurements: ["level"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "float_switch", title: "Schwimmerschalter", measurements: ["level"], signal: "digital", capabilities: ["capability.digital_input"] }),
      sensor({ id: "acs712", title: "ACS712 Stromsensor", measurements: ["current"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "voltage_divider", title: "Spannungsteiler-Messung", measurements: ["voltage"], signal: "analog", capabilities: ["capability.analog_input"] }),
      sensor({ id: "bmp280", title: "BMP280 Drucksensor", measurements: ["pressure"], signal: "i2c", capabilities: ["capability.i2c"] }),
      sensor({ id: "load_cell_hx711", title: "Waegezelle mit HX711", measurements: ["weight", "force"], signal: "digital", capabilities: ["capability.digital_input"] }),
      cameraSensor({ id: "ov2640", title: "OV2640 Kamerasensor", maximumResolution: "1600x1200", colorType: "color", outputFormats: ["JPEG", "YUV422", "RGB565"] }),
      cameraSensor({ id: "ov3660", title: "OV3660 Kamerasensor", maximumResolution: "2048x1536", colorType: "color", outputFormats: ["JPEG", "YUV422", "RGB565"] }),
      cameraSensor({ id: "ov5640", title: "OV5640 Kamerasensor", maximumResolution: "2592x1944", colorType: "color", outputFormats: ["JPEG", "YUV422", "RGB565"] }),
      cameraSensor({ id: "gc2145", title: "GC2145 Kamerasensor", maximumResolution: "1600x1200", colorType: "color", outputFormats: ["YUV422", "RAW Bayer", "RGB565"] }),
      cameraSensor({ id: "gc0308", title: "GC0308 Kamerasensor", maximumResolution: "640x480", colorType: "color", outputFormats: ["YUV422", "RAW Bayer", "RGB565", "Grayscale"] }),
      esp32Board({
        hardware_item_id: "hardware.processor_board.espressif_esp32_c6_devkitc_1",
        sku: "GNX-ESP32-C6-DEVKITC-1",
        title: "Espressif ESP32-C6-DevKitC-1",
        summary: "Offizielles Espressif-Development-Board fuer ESP32-C6-WROOM-Module.",
        vendor: "Espressif",
        module_name: "ESP32-C6-WROOM-1",
        mcu_variant: "ESP32-C6",
      }),
      {
        hardware_item_id: "hardware.module.rfid_rc522",
        sku: "GNX-RFID-RC522",
        item_type: "module",
        title: "RFID RC522 Modul",
        summary: "RFID-Leser fuer Tags und Karten im SPI-Bus.",
        capability_ids: ["capability.spi", "capability.rfid_reading", "capability.item_identification"],
        support_policy: "component_support",
        provisioning_profile_id: "",
        status: "active",
      },
      {
        hardware_item_id: "hardware.actuator.micro_servo",
        sku: "GNX-SERVO-MICRO",
        item_type: "actuator",
        title: "Micro Servo",
        summary: "Kleiner Servo fuer Sperren, Klappen und mechanische Lernprojekte.",
        capability_ids: ["capability.servo_control", "capability.mechanical_locking", "capability.fallback_unlock"],
        support_policy: "component_support",
        provisioning_profile_id: "",
        status: "active",
      },
    ],
  };
}

function boardFeatureOptions() {
  return [
    boardFeature("camera", "Kamera", "capability.camera_input", {
      hardware_options: options(["OV2640", "OV3660", "OV5640", "GC2145", "GC0308"]),
      driver_options: options(["Espressif esp32-camera"]),
      connection_options: options(["Parallel DVP + SCCB"]),
      datasheet_hint: "Sensor, Board-Pinbelegung, XCLK, PSRAM und unterstütztes Pixelformat gemeinsam prüfen.",
    }),
    boardFeature("display", "Display", "capability.display_output", {
      hardware_options: options(["TFT-LCD", "IPS-LCD", "OLED", "E-Paper"]),
      driver_options: options(["ST7789", "ILI9341", "ILI9488", "ST7735", "GC9A01", "SSD1306", "SH1106"]),
      connection_options: options(["SPI", "I2C", "RGB parallel", "8080 parallel", "MIPI DSI"]),
      datasheet_hint: "Controller-Aufdruck, Displaygröße, Auflösung, Pinbelegung und Versorgungsspannung im Board-Datenblatt prüfen.",
    }),
    boardFeature("touch", "Touch", "capability.touchscreen_input", {
      hardware_options: options(["Kapazitiv", "Resistiv"]),
      driver_options: options(["GT911", "FT6236", "FT6336G", "CST816", "XPT2046"]),
      connection_options: options(["I2C", "SPI", "GPIO Interrupt"]),
      datasheet_hint: "Touchcontroller und Interrupt-/Reset-Pins stehen meist separat im Schaltplan des Boards.",
    }),
    boardFeature("speaker", "Speaker", "capability.audio_output", {
      hardware_options: options(["Passiver Lautsprecher", "Aktiver Buzzer", "I2S-Verstärker"]),
      driver_options: options(["Direkt per PWM", "MAX98357A", "NS4168", "ES8311"]),
      connection_options: options(["PWM", "DAC", "I2S"]),
      datasheet_hint: "Verstärker, Impedanz und zulässige Leistung vor dem Flashen prüfen.",
    }),
    boardFeature("microphone", "Mikrofon", "capability.audio_input", {
      hardware_options: options(["Analoges Mikrofon", "I2S-Mikrofon", "PDM-Mikrofon"]),
      driver_options: options(["INMP441", "ICS-43434", "SPH0645", "ES7210", "Analog/ADC"]),
      connection_options: options(["ADC", "I2S", "PDM"]),
      datasheet_hint: "Takt, Kanalwahl und Versorgungsspannung des Mikrofonmoduls im Datenblatt prüfen.",
    }),
    boardFeature("bluetooth", "Bluetooth", "capability.bluetooth", {
      hardware_options: options(["Bluetooth Classic", "Bluetooth Low Energy", "Classic + BLE"]),
      driver_options: options(["ESP-IDF Bluetooth", "NimBLE", "Arduino BLE"]),
      connection_options: options(["Im Prozessor integriert"]),
      datasheet_hint: "Nicht jede ESP-Variante unterstützt Bluetooth Classic. Maßgeblich ist das konkrete MCU-Datenblatt.",
    }),
    boardFeature("wifi", "WLAN", "capability.wifi", {
      hardware_options: options(["2,4 GHz", "2,4 + 5 GHz"]),
      driver_options: options(["ESP-IDF Wi-Fi", "Arduino WiFi"]),
      connection_options: options(["PCB-Antenne", "Externe Antenne / U.FL"]),
      datasheet_hint: "Antennenvariante und zulässige Funkbänder anhand der exakten Modulbezeichnung prüfen.",
    }),
    boardFeature("ram", "Interner SRAM", "capability.external_ram", {
      hardware_options: options(["Interner SRAM"]),
      driver_options: options(["ESP-IDF Heap"]),
      connection_options: options(["Im Prozessor integriert"]),
      value_options: options(["400 KB", "512 KB", "640 KB"]),
      datasheet_hint: "Der interne SRAM gehoert zum SoC und ist vom externen PSRAM getrennt zu erfassen.",
    }),
    boardFeature("psram", "PSRAM", "capability.external_ram", {
      hardware_options: options(["QSPI-PSRAM", "OPI-PSRAM"]),
      driver_options: options(["ESP-IDF Heap/PSRAM", "Arduino PSRAM"]),
      connection_options: options(["Im Modul integriert", "Extern auf dem Board"]),
      value_options: options(["2 MB", "4 MB", "8 MB", "16 MB"]),
      datasheet_hint: "Die PSRAM-Größe folgt der vollständigen Modul-/Boardbezeichnung, nicht nur dem Prozessortyp.",
    }),
    boardFeature("flash", "Flash", "capability.flash_storage", {
      hardware_options: options(["QSPI-Flash", "OPI-Flash"]),
      driver_options: options(["ESP-IDF Partition Table", "Arduino Partition Scheme"]),
      connection_options: options(["Im Modul integriert", "Extern auf dem Board"]),
      value_options: options(["2 MB", "4 MB", "8 MB", "16 MB", "32 MB"]),
      datasheet_hint: "Flash-Größe und Partitionslayout müssen vor OTA und Basissoftware-Flash eindeutig feststehen.",
    }),
    boardFeature("storage", "Speicherkarte", "capability.removable_storage", {
      hardware_options: options(["TF-/microSD-Kartenslot"]),
      driver_options: options(["SD_MMC", "Arduino SD"]),
      connection_options: options(["SDMMC", "SPI"]),
      datasheet_hint: "Busbreite, Kartenversorgung und fest belegte CLK-/CMD-/Datenpins im Board-Schaltplan prüfen.",
    }),
  ];
}

function boardFeature(id, title, capabilityId, details) {
  return {
    hardware_item_id: `hardware.board_feature.${id}`,
    sku: `GNX-BOARD-FEATURE-${id.toUpperCase()}`,
    item_type: "board_feature_option",
    feature_id: id,
    title,
    summary: `${title} am konkreten Board erfassen.`,
    capability_ids: [capabilityId],
    support_policy: "catalog_reference",
    provisioning_profile_id: "",
    status: "active",
    ...details,
  };
}

function options(values) {
  return values.map((title) => ({ id: title.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""), title }));
}

function avrBoard(input) {
  return {
    hardware_item_id: input.hardware_item_id,
    sku: input.sku,
    item_type: "processor_board",
    title: input.title,
    summary: input.summary,
    processor_family: "avr_8bit",
    mcu_variant: input.mcu_variant,
    module_name: "",
    vendor: input.vendor || "",
    form_factor: input.form_factor || "",
    capability_ids: ["capability.processor_avr_8bit", "capability.processor_arduino_avr", "capability.arduino_framework_runtime", "capability.atmel_avr_bare_metal_runtime", "capability.usb_identification", "capability.flash_firmware", "capability.digital_input", "capability.digital_output"],
    identification_methods: ["web_serial_stk500v1_experimental"],
    support_policy: "community_supported",
    provisioning_profile_id: "",
    basissoftware_profile_id: "",
    factory_firmware_artifact: null,
    min_basissoftware_version: "",
    pin_profile: {
      analog_inputs: ["A0", "A1", "A2", "A3", "A4", "A5", "A6", "A7"],
      digital_pins: ["D2", "D3", "D4", "D5", "D6", "D7", "D8", "D9", "D10", "D11", "D12", "D13"],
      pwm_pins: ["D3", "D5", "D6", "D9", "D10", "D11"],
      i2c: ["SDA A4 + SCL A5"],
    },
    platformio_build: {
      platform: "atmelavr",
      board: "nanoatmega328",
      environment: "nanoatmega328",
      framework: "arduino",
      supported_frameworks: ["arduino", ""],
      monitor_speed: 9600,
      upload_protocol: "arduino",
      maximum_program_size_bytes: 30720,
      maximum_ram_size_bytes: 2048,
      firmware_basis_id: "",
    },
    default_instance_configuration: {
      board_features: {
        flash: { enabled: true, hardware: "internal_flash", value: "32_kb" },
        ram: { enabled: true, hardware: "internal_sram", value: "2_kb" },
      },
    },
    status: "active",
  };
}

function esp8266Board(input) {
  const isD1Mini = input.hardware_item_id === "hardware.processor_board.wemos_d1_mini_esp12f";
  return networkBoard({
    ...input,
    processor_family: "esp8266",
    mcu_variant: input.mcu_variant || "ESP8266EX",
    capability_ids: ["capability.processor_esp8266", "capability.wifi", "capability.device_http_status", "capability.captive_setup_supported", "capability.basissoftware_supported", "capability.usb_identification", "capability.flash_firmware", "capability.digital_input", "capability.digital_output", ...(input.extra_capability_ids || [])],
    basissoftware_profile_id: "basissoftware.profile.esp8266_factory",
    provisioning_profile_id: "provisioning_profile.esp8266_basissoftware",
    min_basissoftware_version: "0.1.0",
    platformio_build: input.platformio_build || {
      platform: "espressif8266",
      board: isD1Mini ? "d1_mini" : "esp12e",
      environment: isD1Mini ? "d1_mini" : "esp12e",
      framework: "arduino",
      supported_frameworks: ["arduino"],
      monitor_speed: 115200,
      upload_protocol: "esptool",
      flash_size_mb: 4,
      firmware_basis_id: "",
    },
    default_instance_configuration: input.default_instance_configuration || {
      board_features: {
        flash: { enabled: true, hardware: "qspi_flash", value: "4_mb" },
        ram: { enabled: true, hardware: "internal_sram", value: "80_kb" },
        wifi: { enabled: true, hardware: "2_4_ghz", driver: "arduino_wifi" },
      },
    },
    pin_profile: input.pin_profile || {
      analog_inputs: ["A0"],
      digital_pins: ["D1 / GPIO5", "D2 / GPIO4", "D5 / GPIO14", "D6 / GPIO12", "D7 / GPIO13"],
      pwm_pins: ["D1 / GPIO5", "D2 / GPIO4", "D5 / GPIO14", "D6 / GPIO12", "D7 / GPIO13"],
      i2c: ["SDA D2 / GPIO4 + SCL D1 / GPIO5"],
    },
    verification_status: input.verification_status,
    evidence: input.evidence,
  });
}

function esp32Board(input) {
  const itemId = input.hardware_item_id;
  const isEs3c28p = itemId === "hardware.processor_board.esp32_s3_es3c28p";
  const isCamera = itemId === "hardware.processor_board.ai_thinker_esp32_cam";
  const isNanoEsp32 = itemId === "hardware.processor_board.arduino_nano_esp32";
  const isS3 = /esp32_s3|esp32-s3/.test(itemId) || String(input.mcu_variant || "").includes("S3");
  return networkBoard({
    ...input,
    processor_family: "esp32",
    capability_ids: ["capability.processor_esp32", "capability.wifi", "capability.ota", "capability.device_http_status", "capability.captive_setup_supported", "capability.basissoftware_supported", "capability.usb_identification", "capability.flash_firmware", "capability.digital_input", "capability.digital_output", ...(input.extra_capability_ids || [])],
    basissoftware_profile_id: "basissoftware.profile.esp32_factory",
    provisioning_profile_id: "provisioning_profile.esp32_ota_bootstrap",
    min_basissoftware_version: "0.1.0",
    pin_profile: input.pin_profile || {
      analog_inputs: ["GPIO32 / ADC1_CH4", "GPIO33 / ADC1_CH5", "GPIO34 / ADC1_CH6", "GPIO35 / ADC1_CH7", "GPIO36 / ADC1_CH0", "GPIO39 / ADC1_CH3"],
      digital_pins: ["GPIO4", "GPIO5", "GPIO12", "GPIO13", "GPIO14", "GPIO16", "GPIO17", "GPIO18", "GPIO19", "GPIO21", "GPIO22", "GPIO23", "GPIO25", "GPIO26", "GPIO27"],
      pwm_pins: ["GPIO4", "GPIO5", "GPIO12", "GPIO13", "GPIO14", "GPIO18", "GPIO19", "GPIO23", "GPIO25", "GPIO26", "GPIO27"],
      i2c: ["SDA GPIO21 + SCL GPIO22"],
    },
    default_instance_configuration: input.default_instance_configuration,
    verification_status: input.verification_status,
    evidence: input.evidence,
    peripheral_profile: esp32PeripheralProfile(input.mcu_variant),
    platformio_build: input.platformio_build || (isEs3c28p ? {
      platform: "espressif32", board: "esp32-s3-devkitc-1", environment: "es3c28p", framework: "arduino",
      monitor_speed: 115200, upload_protocol: "esptool", flash_size_mb: 16,
      supported_frameworks: ["arduino", "espidf"],
      libraries: ["lovyan03/LovyanGFX@^1.2.7"], build_flags: ["-D ARDUINO_USB_MODE=1", "-D ARDUINO_USB_CDC_ON_BOOT=1"],
      firmware_basis_id: "",
    } : isCamera ? {
      platform: "espressif32", board: "esp32cam", environment: "esp32cam", framework: "arduino",
      monitor_speed: 115200, upload_protocol: "esptool", flash_size_mb: 4, firmware_basis_id: "",
      supported_frameworks: ["arduino"],
    } : isNanoEsp32 ? {
      platform: "espressif32", board: "arduino_nano_esp32", environment: "arduino_nano_esp32", framework: "arduino",
      monitor_speed: 115200, upload_protocol: "esptool", flash_size_mb: 16, firmware_basis_id: "",
      supported_frameworks: ["arduino"],
    } : {
      platform: "espressif32", board: isS3 ? "esp32-s3-devkitc-1" : "esp32dev", environment: isS3 ? "esp32-s3-devkitc-1" : "esp32dev",
      framework: "espidf", monitor_speed: 115200, upload_protocol: "esptool", flash_size_mb: 4,
      supported_frameworks: ["espidf", "arduino"],
      firmware_basis_id: "gernetix-runtime-basissoftware", firmware_basis_version: "workspace", firmware_basis_variant: "full",
    }),
    factory_firmware_artifact: {
      artifact_id: "firmware_artifact.esp32_basissoftware_factory.latest",
      source: "sqlite",
      uri: "sqlite://provisioning_firmware_artifacts/firmware_artifact.esp32_basissoftware_factory.latest",
      version: "latest",
      sha256: "",
    },
  });
}

function flashbox(input) {
  return {
    hardware_item_id: input.hardware_item_id,
    sku: input.sku,
    item_type: "flashbox",
    hardware_class: "flashbox",
    title: input.title,
    summary: input.summary,
    processor_family: "esp32",
    mcu_variant: input.mcu_variant || "ESP32-S3",
    module_name: input.module_name || "ESP32-S3-WROOM-1",
    module_memory_variant: input.module_memory_variant || "N16R8",
    firmware_build_target_id: "firmware_build_target.esp32_s3_opi_n16r8",
    vendor: input.vendor || "GerNetiX",
    form_factor: input.form_factor || "displayless_dual_usb_helper",
    capability_ids: [
      "capability.processor_esp32",
      "capability.wifi",
      "capability.ota",
      "capability.bluetooth",
      "capability.device_http_status",
      "capability.usb_identification",
      "capability.usb_otg_host",
      "capability.flash_firmware",
      "capability.flashbox_target_flash",
      "capability.flashbox_self_update",
      "capability.flashbox_manifest_download",
    ],
    flashbox_capability_keys: [
      "flashbox.self_update",
      "flashbox.usb_otg_target_detection",
      "flashbox.target_flash",
      "flashbox.signed_manifest_download",
      "flashbox.inventory_claim",
    ],
    supported_target_families: ["esp32", "esp32-s3", "esp32-c3", "esp32-c6"],
    identification_methods: ["gernetix_claim_code", "factory_serial", "account_inventory"],
    support_policy: "gernetix_purchase_only",
    purchase_policy: "gernetix_purchase_only",
    inventory_policy: "claim_required",
    self_creation_allowed: false,
    provisioning_profile_id: "provisioning_profile.flashbox_factory",
    basissoftware_profile_id: "basissoftware.profile.flashbox_factory",
    factory_firmware_artifact: {
      artifact_id: "firmware_artifact.flashbox_factory.latest",
      source: "vps_manifest",
      uri: "https://vps.gernetix.example/firmware/flashbox/latest/manifest.json",
      version: "latest",
      sha256: "",
    },
    min_basissoftware_version: "0.1.0",
    min_flashbox_firmware_version: "0.1.0",
    default_instance_configuration: {
      role: "flashbox",
      target_flash_transport: "usb_otg",
      self_update_policy: "a_b_verified_rollback",
      requires_purchase_claim: true,
      ui: { mode: "displayless_http_serial_status", display_enabled: false, touch_enabled: false },
      usb_ports: {
        control: { role: "control_upstream_power_and_service", verification_status: "pending_new_board_test" },
        target: { role: "target_downstream_usb_host", verification_status: "pending_new_board_test" },
      },
      wireless_setup: { wifi: true, ble: true },
      usb_otg_power: {
        vbus_power_mode: "two_usb_s3_helper_target_vbus_pending_verification",
        vbus_power_switch_pin: null,
        vbus_boost_enable_pin: null,
        vbus_source_select_pin: null,
        vbus_current_limit_enable_pin: null,
        software_vbus_switching: "pending_two_usb_s3_board_verification",
        unpowered_targets_require_external_power: true,
        battery_input: { documented: false, adc_pin: null, voltage_divider: null },
        required_product_verification: "two_usb_s3_helper_target_vbus_hardware_test",
        schematic_conclusion: "pending_new_two_usb_s3_board_schematic",
      },
    },
    verification_status: "gernetix_product_stub",
    evidence: {
      requirement_package: "flashbox_bootstrap_and_recovery",
      testability: "catalog_shop_claim_inventory_slice",
    },
    pin_profile: {},
    peripheral_profile: esp32PeripheralProfile(input.mcu_variant || "ESP32-S3"),
    status: "active",
  };
}

function networkBoard(input) {
  return {
    hardware_item_id: input.hardware_item_id,
    sku: input.sku,
    item_type: "processor_board",
    title: input.title,
    summary: input.summary,
    processor_family: input.processor_family,
    mcu_variant: input.mcu_variant,
    module_name: input.module_name || "",
    module_memory_variant: input.module_memory_variant || "",
    usb_serial_chip: input.usb_serial_chip || "",
    cpu_architecture: input.cpu_architecture || "",
    cpu_core: input.cpu_core || "",
    clock_hz: Number(input.clock_hz) || 0,
    firmware_build_target_id: input.firmware_build_target_id
      || (input.mcu_variant === "ESP32" ? "firmware_build_target.esp32_classic_qspi_4mb" : "")
      || (input.mcu_variant === "ESP32-C6" ? "firmware_build_target.esp32_c6_qspi_4mb" : ""),
    platformio_build: input.platformio_build || {},
    vendor: input.vendor || "Generic",
    form_factor: input.form_factor || "",
    capability_ids: input.capability_ids,
    identification_methods: ["network_http_status", "web_serial_bootloader"],
    support_policy: "gernetix_verified_after_provisioning",
    provisioning_profile_id: input.provisioning_profile_id,
    basissoftware_profile_id: input.basissoftware_profile_id,
    factory_firmware_artifact: input.factory_firmware_artifact || null,
    min_basissoftware_version: input.min_basissoftware_version || "",
    default_instance_configuration: input.default_instance_configuration || {
      online_led: { configurable: true },
      display: { configurable: true, optional: true },
      sound: { configurable: true, optional: true },
    },
    verification_status: input.verification_status || "catalog_seed",
    evidence: input.evidence || {},
    pin_profile: input.pin_profile || {},
    peripheral_profile: input.peripheral_profile || {},
    status: "active",
  };
}

function esp32PeripheralProfile(mcuVariant = "ESP32") {
  return {
    schema_version: 1,
    documentation_url: esp32PeripheralDocumentationUrl(mcuVariant),
    resources: [
      peripheral("gpio", "GPIO", "Digitale Ein- und Ausgänge", { configurable: true, pin_profile_key: "digital_pins" }),
      peripheral("adc", "ADC", "Analoge Signale digital erfassen", { configurable: true, pin_profile_key: "analog_inputs" }),
      peripheral("pwm", "PWM", "Pulsweitenmodulierte Ausgänge", { configurable: true, pin_profile_key: "pwm_pins" }),
      peripheral("i2c", "I²C", "Zweidraht-Bus für Sensoren und Erweiterungen", { configurable: true, pin_profile_key: "i2c" }),
      peripheral("spi", "SPI", "Synchroner serieller Hochgeschwindigkeitsbus", { configurable: true }),
      peripheral("uart", "UART", "Asynchrone serielle Kommunikation", { configurable: true }),
      peripheral("pcnt", "PCNT", "Hardware-Impuls- und Quadraturzähler", { configurable: true }),
      peripheral("rmt", "RMT", "Präzise Pulsfolgen senden und empfangen", { configurable: true }),
      peripheral("i2s", "I²S", "Digitale Audio- und Datenströme", { configurable: true }),
      peripheral("twai", "TWAI / CAN", "CAN-kompatible Feldbuskommunikation", { configurable: true }),
      peripheral("mcpwm", "Motor-PWM", "Mehrkanal-PWM mit Totzeit für Motorsteuerungen", { configurable: true }),
      peripheral("hardware_timer", "Hardware-Timer", "Zeitbasis für Scheduler, Regelung und präzise Ereignisse", { managed_by: "runtime_timer" }),
      peripheral("interrupt", "Interrupt-Controller", "Ereignisgesteuerte Reaktion auf Peripherie und Pins", { managed_by: "runtime_events" }),
    ],
    abstractions: [
      abstraction("runtime_timer", "Zeitgeber", "OS/Basissoftware verwaltet Zeitpunkte, Intervalle und Scheduler-Ticks.", ["hardware_timer"]),
      abstraction("runtime_events", "Ereignisse", "Interrupts werden als sichere Ereignisse und Callbacks bereitgestellt.", ["interrupt", "gpio"]),
      abstraction("digital_io", "Digital-I/O", "Einheitlicher Zugriff auf digitale Ein- und Ausgänge.", ["gpio"]),
      abstraction("analog_input", "Analogeingang", "Kalibrierte Messwerte statt direkter ADC-Registerzugriffe.", ["adc"]),
      abstraction("measurement_acquisition", "Messwerterfassung", "Sensorwerte zyklisch erfassen, kalibrieren und als einheitliche Messwerte bereitstellen.", ["runtime_timer", "analog_input", "serial_bus"]),
      abstraction("waveform_output", "Puls- und Wellenformausgabe", "Zeitgesteuerte Ausgaben über PWM, Motor-PWM oder RMT.", ["pwm", "mcpwm", "rmt", "hardware_timer"]),
      abstraction("serial_bus", "Serielle Busse", "Treiberzugriff auf I²C, SPI, UART, I²S und TWAI.", ["i2c", "spi", "uart", "i2s", "twai"]),
    ],
    drivers: [
      driver("data_logger", "Datenlogger", "Messwerte in konfigurierbaren Intervallen sammeln, zusammenfassen und an ein Speicherziel übergeben.", ["measurement_acquisition", "runtime_timer"], { configures: "sensor" }),
      driver("servo_driver", "Servo-Treiber", "Positionsvorgabe über zeitgenaue PWM-Signale.", ["waveform_output", "pwm"]),
      driver("dc_motor_driver", "DC-Motortreiber / H-Brücke", "Drehzahl und Richtung über PWM und digitale Ausgänge.", ["waveform_output", "pwm", "gpio"]),
      driver("stepper_driver", "Schrittmotor-Treiber", "STEP/DIR-Signale mit deterministischer Zeitbasis.", ["runtime_timer", "gpio", "rmt"]),
      driver("synchronous_motor_driver", "Synchronmotor / BLDC / PMSM", "Kommutierung oder FOC über 3-Phasen-Leistungstreiber, Motor-PWM, Strommessung und Rotorlage.", ["mcpwm", "adc", "hardware_timer", "pcnt"]),
    ],
  };
}

function esp32PeripheralDocumentationUrl(mcuVariant) {
  const normalized = String(mcuVariant || "").toLowerCase();
  if (normalized.includes("s3")) return "https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/api-reference/peripherals/index.html";
  if (normalized.includes("c6")) return "https://docs.espressif.com/projects/esp-idf/en/latest/esp32c6/api-reference/peripherals/index.html";
  return "https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/index.html";
}

function peripheral(id, title, description, options = {}) {
  return { id, title, description, configurable: false, ...options };
}

function abstraction(id, title, description, dependsOn) {
  return { id, title, description, depends_on: dependsOn };
}

function driver(id, title, description, dependsOn, options = {}) {
  return { id, title, description, depends_on: dependsOn, configures: "actuator", ...options };
}

function capability(capabilityId, title) {
  return {
    capability_id: capabilityId,
    title,
    owner_domain: "Hardware",
    status: "active",
  };
}

function sensor(input) {
  return {
    hardware_item_id: `hardware.sensor.${input.id}`,
    sku: `GNX-SENSOR-${input.id.toUpperCase().replace(/[^A-Z0-9]+/g, "-")}`,
    item_type: "sensor",
    sensor_type_id: input.id,
    title: input.title,
    summary: input.summary || input.title,
    measurement_kinds: input.measurements,
    signal_type: input.signal,
    component_class: input.componentClass || "measurement_sensor",
    interface: input.interface || input.signal,
    driver_id: input.driverId || "",
    maximum_resolution: input.maximumResolution || "",
    color_type: input.colorType || "",
    output_formats: input.outputFormats || [],
    capability_ids: input.capabilities,
    support_policy: "component_support",
    provisioning_profile_id: "",
    status: "active",
  };
}

function cameraSensor(input) {
  return sensor({
    ...input,
    measurements: ["image"],
    signal: "parallel_dvp_sccb",
    capabilities: ["capability.camera_input"],
    componentClass: "camera_sensor",
    interface: "parallel_dvp_sccb",
    driverId: "espressif_esp32_camera",
    summary: `${input.title}, unterstützt durch den Espressif-Treiber esp32-camera.`,
  });
}

module.exports = { defaultCatalogSeed };
