const RESERVED_PLATFORMIO_OPTIONS = new Set([
  "platform", "board", "framework", "monitor_speed", "upload_protocol", "upload_speed",
  "board_build.flash_size", "board_upload.flash_size", "board_upload.maximum_size",
  "board_upload.maximum_ram_size", "board_build.partitions", "lib_deps", "build_flags",
]);

function renderPlatformioIni(input = {}) {
  const config = input && typeof input === "object" ? input : {};
  const environment = stringValue(config.environment) || stringValue(config.board) || "default";
  const lines = [
    "; Generated by GerNetiX from the immutable project board snapshot.",
    "; Change the graphical board configuration and save to regenerate this file.",
    "[platformio]",
    `default_envs = ${environment}`,
    "",
    `[env:${environment}]`,
    `platform = ${stringValue(config.platform) || "espressif32"}`,
    `board = ${stringValue(config.board) || "esp32dev"}`,
  ];
  const framework = stringValue(config.framework);
  if (framework) lines.push(`framework = ${framework}`);
  lines.push(`monitor_speed = ${positiveInteger(config.monitor_speed ?? config.monitorSpeed) || 115200}`);
  const uploadProtocol = stringValue(config.upload_protocol ?? config.uploadProtocol);
  if (uploadProtocol) lines.push(`upload_protocol = ${uploadProtocol}`);
  const uploadSpeed = positiveInteger(config.upload_speed ?? config.uploadSpeed);
  if (uploadSpeed) lines.push(`upload_speed = ${uploadSpeed}`);

  const flashSizeMb = effectiveFlashSizeMb(config);
  if (flashSizeMb && /^espressif(32|8266)$/i.test(String(config.platform || ""))) {
    lines.push(`board_build.flash_size = ${flashSizeMb}MB`);
    lines.push(`board_upload.flash_size = ${flashSizeMb}MB`);
  }
  const maximumProgramSize = positiveInteger(config.maximum_program_size_bytes);
  const maximumRamSize = positiveInteger(config.maximum_ram_size_bytes);
  if (maximumProgramSize) lines.push(`board_upload.maximum_size = ${maximumProgramSize}`);
  if (maximumRamSize) lines.push(`board_upload.maximum_ram_size = ${maximumRamSize}`);

  const partitionFile = platformioPartitionFile(config, flashSizeMb);
  if (partitionFile) lines.push(`board_build.partitions = ${partitionFile}`);

  const libraries = stringList(config.libraries);
  if (libraries.length) {
    lines.push("lib_deps =");
    for (const library of libraries) lines.push(`  ${library}`);
  }
  const buildFlags = effectiveBuildFlags(config);
  if (buildFlags.length) {
    lines.push("build_flags =");
    for (const flag of buildFlags) lines.push(`  ${flag}`);
  }
  for (const [key, value] of Object.entries(normalizeExtraOptions(config.platformio_options))) {
    lines.push(`${key} = ${value}`);
  }
  lines.push("");
  return lines.join("\n");
}

function effectiveFlashSizeMb(config = {}) {
  const explicit = Number(config.flash_size_mb);
  if (Number.isInteger(explicit) && explicit > 0) return explicit;
  const value = String(config.board_configuration?.board_features?.flash?.value || "").trim().toLowerCase();
  const match = value.match(/^(\d+)_mb$/);
  return match ? Number(match[1]) : 0;
}

function effectiveBuildFlags(config = {}) {
  const flags = stringList(config.build_flags);
  if (config.firmware_basis_id) {
    const profile = String(config.firmware_basis_variant || "full").toLowerCase() === "comfort"
      ? "full"
      : String(config.firmware_basis_variant || "full").toLowerCase();
    flags.push(`-D GERNETIX_BASISSOFTWARE_PROFILE_${profile.toUpperCase()}=1`);
    if (config.board_configuration) flags.push("-include include/gernetix_board_configuration.h");
    if (config.basissoftware_configuration) flags.push("-include include/gernetix_basissoftware_configuration.h");
  }
  return Array.from(new Set(flags));
}

function platformioPartitionFile(config = {}, flashSizeMb = effectiveFlashSizeMb(config)) {
  const explicit = stringValue(config.partition_file);
  if (explicit) return explicit;
  if (!config.firmware_basis_id || !flashSizeMb) return "";
  const profile = String(config.firmware_basis_variant || "full").toLowerCase() === "comfort"
    ? "full"
    : String(config.firmware_basis_variant || "full").toLowerCase();
  return `partitions_${profile}_${flashSizeMb}mb.csv`;
}

function normalizeExtraOptions(input) {
  if (!input || typeof input !== "object" || Array.isArray(input)) return {};
  return Object.fromEntries(Object.entries(input).slice(0, 30)
    .map(([key, value]) => [String(key).trim(), String(value).trim()])
    .filter(([key, value]) => /^[a-z][a-z0-9_.-]{0,79}$/i.test(key)
      && !RESERVED_PLATFORMIO_OPTIONS.has(key.toLowerCase())
      && value
      && !/[\r\n]/.test(value)));
}

function stringList(input) {
  return Array.from(new Set((Array.isArray(input) ? input : [])
    .map((value) => String(value || "").trim())
    .filter((value) => value && !/[\r\n]/.test(value))));
}

function stringValue(value) {
  const normalized = String(value || "").trim();
  return /[\r\n]/.test(normalized) ? "" : normalized;
}

function positiveInteger(value) {
  const normalized = Number(value);
  return Number.isInteger(normalized) && normalized > 0 ? normalized : 0;
}

module.exports = {
  effectiveBuildFlags,
  effectiveFlashSizeMb,
  platformioPartitionFile,
  renderPlatformioIni,
};
