[platformio]
default_envs = diymore_hw_364a

[env:diymore_hw_364a]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_protocol = esptool
board_build.flash_mode = dio
board_build.f_flash = 40000000L
board_build.f_cpu = 80000000L
board_build.filesystem = littlefs
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  olikraus/U8g2@^2.36.17
build_flags =
  -D GERNETIX_BASISSOFTWARE_VERSION=\"0.1.0\"
  -D GERNETIX_HARDWARE_PROFILE=\"hardware.processor_board.diymore_hw_364a_esp8266_oled\"
